import type { Artboard, Component, Id, Snapshot } from '@loom/ir';
import { CompileError, type EmitContext } from '../types';
import { emitterFor, knownComponentTypes } from '../templates/registry';
import { pathExpression, type RouteMap } from './routes';
import { valueExpr } from './props';

const PARAMS_VAR = 'params';
const NAVIGATE_VAR = 'navigate';

/** Walk one artboard's component tree into a React function component module. */
export function emitArtboardModule(
  snapshot: Snapshot,
  artboard: Artboard,
  routes: RouteMap,
  componentName: string,
): string {
  const component = (id: Id): Component => {
    const found = snapshot.components[id];
    if (!found) throw new CompileError(`Unknown component id "${id}".`, id);
    return found;
  };

  const seen = new Set<Id>();
  const hooks = { params: false, navigate: false };

  const ctx: EmitContext = {
    snapshot,
    artboard,
    routes,
    component,
    renderChild: (id, depth) => render(id, depth),
    requireParams: () => {
      hooks.params = true;
      return PARAMS_VAR;
    },
    requireNavigate: () => {
      hooks.navigate = true;
      return NAVIGATE_VAR;
    },
    navigateExpr: (flowId, componentId) => {
      const flow = snapshot.flows[flowId];
      if (!flow) throw new CompileError(`Unknown flow "${flowId}".`, componentId);
      if (flow.from !== artboard.id) {
        throw new CompileError(
          `Flow "${flowId}" starts on a different artboard than the component using it.`,
          componentId,
        );
      }
      const destination = routes.get(flow.to);
      if (!destination) throw new CompileError(`Flow "${flowId}" has no destination.`, componentId);

      const values = new Map<string, string>();
      for (const entry of flow.payload ?? []) {
        if (entry.kind === 'bound') {
          throw new CompileError(
            `Flow payload for "${entry.param}" reads a node port, which needs the binding runtime (M3).`,
            componentId,
          );
        }
        // An empty value would emit a path that no route matches — treat it as missing.
        if (entry.value === null || entry.value === undefined || entry.value === '') continue;
        values.set(entry.param, JSON.stringify(entry.value));
      }

      return `${ctx.requireNavigate()}(${pathExpression(destination, values)})`;
    },
  };

  function render(id: Id, depth: number): string {
    // A component reachable twice means the tree is not a tree; emitting it would
    // duplicate state silently.
    if (seen.has(id)) {
      throw new CompileError(`Component "${id}" appears twice in the tree (cycle).`, id);
    }
    seen.add(id);

    const target = component(id);
    const emitter = emitterFor(target.type);
    if (!emitter) {
      throw new CompileError(
        `No template for component type "${target.type}". Known types: ${knownComponentTypes().join(', ')}.`,
        id,
      );
    }
    return emitter.emit(target, ctx, depth);
  }

  const tree = render(artboard.root, 2);

  const imports: string[] = [];
  const routerHooks = [hooks.navigate ? 'useNavigate' : null, hooks.params ? 'useParams' : null]
    .filter(Boolean)
    .join(', ');
  if (routerHooks) imports.push(`import { ${routerHooks} } from 'react-router-dom';\n`);

  const prelude: string[] = [];
  if (hooks.navigate) prelude.push(`  const ${NAVIGATE_VAR} = useNavigate();`);
  if (hooks.params) prelude.push(`  const ${PARAMS_VAR} = useParams();`);

  return `// Generated by @loom/compiler from artboard "${artboard.name}" (${artboard.id}).
// Managed region: edits here are overwritten on the next compile.
${imports.join('')}
export default function ${componentName}() {
${prelude.length > 0 ? `${prelude.join('\n')}\n\n` : ''}  return (
${tree}
  );
}
`;
}

/** Re-exported for the templates that read plain property values. */
export { valueExpr };
