import { AUTH_SERVER_PATH } from './auth';
import type { EmittedFile } from '../types';

/**
 * The server half of app auth (`docs/specs/app-auth.md`).
 *
 * Four functions and one shared module. They speak GoTrue's REST API directly, for the same
 * reason a route takes `@supabase/postgrest-js` rather than the umbrella package: a stateless
 * function wants an HTTP call, not a client that builds a realtime connection on import.
 *
 * The shared module lives under `src/server/` rather than in `api/`, because everything in `api/`
 * on Vercel is a route someone could call. A helper is not a route.
 */

const SERVER_MODULE = `// Generated by @loom/compiler. SERVER ONLY — never import this from a component.
// It reads the project's Supabase credentials by name and mints the cookies that hold a session.
import type { IncomingMessage, ServerResponse } from 'node:http';

export interface LoomUser {
  id: string;
  email: string;
}

/** What GoTrue answers a sign-in with. Everything is optional: an error body has none of it. */
export interface AuthSession {
  access_token?: string;
  refresh_token?: string;
  user?: { id?: string; email?: string } | null;
}

export const ACCESS_COOKIE = 'loom_at';
export const REFRESH_COOKIE = 'loom_rt';

// Thirty days: long enough that a person is not signed out for coming back on Monday, and the
// access token inside it still expires every hour regardless.
const COOKIE_MAX_AGE = 60 * 60 * 24 * 30;

const authUrl = (path: string): string => \`\${process.env.SUPABASE_URL ?? ''}/auth/v1\${path}\`;
const anonKey = (): string => process.env.SUPABASE_ANON_KEY ?? '';

/** Every GoTrue call carries the project's publishable key; only some carry a person's token. */
export async function authFetch(path: string, init: RequestInit = {}): Promise<Response> {
  const headers = new Headers(init.headers);
  headers.set('apikey', anonKey());
  if (!headers.has('authorization')) headers.set('authorization', \`Bearer \${anonKey()}\`);
  if (init.body && !headers.has('content-type')) headers.set('content-type', 'application/json');
  return fetch(authUrl(path), { ...init, headers });
}

export function readCookies(req: IncomingMessage): Record<string, string> {
  const jar: Record<string, string> = {};
  for (const part of (req.headers.cookie ?? '').split(';')) {
    const index = part.indexOf('=');
    if (index < 0) continue;
    jar[part.slice(0, index).trim()] = decodeURIComponent(part.slice(index + 1).trim());
  }
  return jar;
}

function cookie(req: IncomingMessage, name: string, value: string, maxAge: number): string {
  // HttpOnly: the browser holds the session but no script can read it.
  // SameSite=Lax: another site cannot make the browser send it on a POST, which is the CSRF answer.
  // Secure only when the request arrived over HTTPS — on http://localhost it would be dropped.
  const https = req.headers['x-forwarded-proto'] === 'https';
  const parts = [
    \`\${name}=\${encodeURIComponent(value)}\`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    \`Max-Age=\${maxAge}\`,
  ];
  if (https) parts.push('Secure');
  return parts.join('; ');
}

export function setSession(req: IncomingMessage, res: ServerResponse, session: AuthSession): void {
  const jar: string[] = [];
  if (session.access_token) jar.push(cookie(req, ACCESS_COOKIE, session.access_token, COOKIE_MAX_AGE));
  if (session.refresh_token) {
    jar.push(cookie(req, REFRESH_COOKIE, session.refresh_token, COOKIE_MAX_AGE));
  }
  if (jar.length > 0) res.setHeader('set-cookie', jar);
}

/** The providers this app was built to accept. Checked in the route as well as at compile time. */
export const PROVIDERS: string[] = __PROVIDERS__;

/** Where the verifier waits between the two halves of the redirect. */
export const VERIFIER_COOKIE = 'loom_pkce';

/**
 * Ten minutes: long enough to sign in with a password manager and a second factor, short enough
 * that an abandoned attempt does not stay armed.
 */
const VERIFIER_MAX_AGE = 60 * 10;

export function pkceCookie(req: IncomingMessage, verifier: string): string {
  return cookie(req, VERIFIER_COOKIE, verifier, VERIFIER_MAX_AGE);
}

export function clearPkceCookie(req: IncomingMessage): string {
  return cookie(req, VERIFIER_COOKIE, '', 0);
}

/**
 * Where this app is, as the browser reached it.
 *
 * Taken from the request rather than from configuration: the same build runs on localhost, on a
 * preview URL and in production, and a redirect_to that named the wrong one would send someone
 * else's browser to someone else's deployment.
 */
export function appOrigin(req: IncomingMessage): string {
  const proto = req.headers['x-forwarded-proto'] === 'https' ? 'https' : 'http';
  const host = req.headers['x-forwarded-host'] ?? req.headers.host ?? 'localhost';
  return \`\${proto}://\${String(host)}\`;
}

export function clearSession(req: IncomingMessage, res: ServerResponse): void {
  res.setHeader('set-cookie', [
    cookie(req, ACCESS_COOKIE, '', 0),
    cookie(req, REFRESH_COOKIE, '', 0),
  ]);
}

/** When the token stops being accepted, in ms. Its own payload says so. */
function expiryOf(token: string): number {
  const payload = token.split('.')[1];
  if (!payload) return 0;
  try {
    const claims = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) as {
      exp?: number;
    };
    return typeof claims.exp === 'number' ? claims.exp * 1000 : 0;
  } catch {
    return 0;
  }
}

/**
 * The caller's access token, refreshed if it has expired.
 *
 * Reading a JWT's own claims without verifying the signature is fine here: the only party whose
 * opinion matters is Supabase, which checks it on every request. This is deciding when to spend
 * the refresh token, not deciding whether someone is who they say.
 */
export async function accessTokenFor(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<string | null> {
  const jar = readCookies(req);
  const access = jar[ACCESS_COOKIE];
  // A minute of margin, so a token that dies mid-request does not come back as a mystery 401.
  if (access && expiryOf(access) > Date.now() + 60_000) return access;

  const refresh = jar[REFRESH_COOKIE];
  if (!refresh) return access ?? null;

  const response = await authFetch('/token?grant_type=refresh_token', {
    method: 'POST',
    body: JSON.stringify({ refresh_token: refresh }),
  });
  if (!response.ok) {
    clearSession(req, res);
    return null;
  }

  const session = (await response.json()) as AuthSession;
  setSession(req, res, session);
  return session.access_token ?? null;
}

/** Who is asking, or nobody. */
export async function userFor(
  req: IncomingMessage,
  res: ServerResponse,
): Promise<LoomUser | null> {
  const token = await accessTokenFor(req, res);
  if (!token) return null;

  const response = await authFetch('/user', { headers: { authorization: \`Bearer \${token}\` } });
  if (!response.ok) return null;

  const body = (await response.json()) as { id?: string; email?: string };
  return body.id ? { id: body.id, email: body.email ?? '' } : null;
}

export function userOf(session: AuthSession): LoomUser | null {
  const user = session.user;
  return user?.id ? { id: user.id, email: user.email ?? '' } : null;
}

export async function readJson(req: IncomingMessage): Promise<Record<string, unknown>> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  if (chunks.length === 0) return {};
  try {
    return JSON.parse(Buffer.concat(chunks).toString('utf8')) as Record<string, unknown>;
  } catch {
    return {};
  }
}

/** GoTrue reports failures in two shapes depending on the endpoint; both end up here. */
export function messageOf(body: unknown, fallback: string): string {
  const failure = (body ?? {}) as { error_description?: string; msg?: string; message?: string };
  return failure.error_description ?? failure.msg ?? failure.message ?? fallback;
}
`;

const SIGN_IN = `// Generated by @loom/compiler. Signing in happens here, on the server, so the tokens can be put
// somewhere the browser cannot read them (docs/specs/app-auth.md).
import type { IncomingMessage, ServerResponse } from 'node:http';
import {
  authFetch,
  messageOf,
  readJson,
  setSession,
  userOf,
  type AuthSession,
} from '../../src/server/auth';

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  res.setHeader('content-type', 'application/json');

  const body = await readJson(req);
  const email = String(body.email ?? '').trim();
  const password = String(body.password ?? '');
  if (!email || !password) {
    res.statusCode = 400;
    res.end(JSON.stringify({ error: 'Enter an email address and a password.' }));
    return;
  }

  const response = await authFetch('/token?grant_type=password', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  const session = (await response.json()) as AuthSession;

  if (!response.ok) {
    // The same sentence whether the address is unknown or the password is wrong: telling them
    // apart tells a stranger which addresses have accounts.
    res.statusCode = 401;
    res.end(JSON.stringify({ error: messageOf(session, 'That email and password did not match.') }));
    return;
  }

  setSession(req, res, session);
  res.statusCode = 200;
  res.end(JSON.stringify({ user: userOf(session) }));
}
`;

const SIGN_UP = `// Generated by @loom/compiler. Creating an account.
import type { IncomingMessage, ServerResponse } from 'node:http';
import {
  authFetch,
  messageOf,
  readJson,
  setSession,
  userOf,
  type AuthSession,
} from '../../src/server/auth';

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  res.setHeader('content-type', 'application/json');

  const body = await readJson(req);
  const email = String(body.email ?? '').trim();
  const password = String(body.password ?? '');
  if (!email || !password) {
    res.statusCode = 400;
    res.end(JSON.stringify({ error: 'Enter an email address and a password.' }));
    return;
  }

  const response = await authFetch('/signup', {
    method: 'POST',
    body: JSON.stringify({ email, password }),
  });
  const session = (await response.json()) as AuthSession;

  if (!response.ok) {
    res.statusCode = response.status;
    res.end(JSON.stringify({ error: messageOf(session, 'That account could not be created.') }));
    return;
  }

  // With email confirmation on, Supabase answers with a user and no session. That is a success
  // that has not signed anyone in, and the app is told so rather than left looking signed out.
  const signedIn = Boolean(session.access_token);
  if (signedIn) setSession(req, res, session);

  res.statusCode = 200;
  res.end(
    JSON.stringify({
      user: signedIn ? userOf(session) : null,
      confirmationRequired: !signedIn,
    }),
  );
}
`;

const SIGN_OUT = `// Generated by @loom/compiler. Signing out clears the cookies whatever Supabase says: a session
// the server refuses to hold is over regardless of what the other end thinks.
import type { IncomingMessage, ServerResponse } from 'node:http';
import { ACCESS_COOKIE, authFetch, clearSession, readCookies } from '../../src/server/auth';

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  res.setHeader('content-type', 'application/json');

  const token = readCookies(req)[ACCESS_COOKIE];
  if (token) {
    try {
      await authFetch('/logout', {
        method: 'POST',
        headers: { authorization: \`Bearer \${token}\` },
      });
    } catch {
      // Their session is ending here either way.
    }
  }

  clearSession(req, res);
  res.statusCode = 200;
  res.end(JSON.stringify({ user: null }));
}
`;

const SESSION = `// Generated by @loom/compiler. Who is here — the one thing the browser is allowed to know.
import type { IncomingMessage, ServerResponse } from 'node:http';
import { userFor } from '../../src/server/auth';

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  res.setHeader('content-type', 'application/json');
  // Never cached: a stale answer here is someone else's name on the screen.
  res.setHeader('cache-control', 'no-store');

  try {
    res.statusCode = 200;
    res.end(JSON.stringify({ user: await userFor(req, res) }));
  } catch (error) {
    res.statusCode = 200;
    res.end(JSON.stringify({ user: null, error: error instanceof Error ? error.message : 'no session' }));
  }
}
`;

const OAUTH_START = `// Generated by @loom/compiler. Where signing in with a provider begins (docs/17-sso.md).
//
// The whole exchange happens on the server, so the tokens land in HttpOnly cookies the same way a
// password sign-in's do. What the browser gets is two redirects and nothing else.
import { createHash, randomBytes } from 'node:crypto';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { PROVIDERS, appOrigin, pkceCookie } from '../../src/server/auth';

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const url = new URL(req.url ?? '/', appOrigin(req));
  const provider = String(url.searchParams.get('provider') ?? '');

  // A closed list, checked here as well as at compile time: this value ends up in a URL, and
  // "whatever was in the query string" is not something to forward to an auth server.
  if (!PROVIDERS.includes(provider)) {
    res.statusCode = 400;
    res.setHeader('content-type', 'text/plain');
    res.end('Unknown sign-in provider.');
    return;
  }

  // PKCE: a secret this server keeps, and a hash of it that travels. The verifier goes into an
  // HttpOnly cookie rather than into the URL, so nothing but this server can complete the flow.
  const verifier = randomBytes(48).toString('base64url');
  const challenge = createHash('sha256').update(verifier).digest('base64url');
  res.setHeader('set-cookie', pkceCookie(req, verifier));

  const authorize = new URL(\`\${process.env.SUPABASE_URL ?? ''}/auth/v1/authorize\`);
  authorize.searchParams.set('provider', provider);
  authorize.searchParams.set('redirect_to', \`\${appOrigin(req)}/api/auth/callback\`);
  authorize.searchParams.set('code_challenge', challenge);
  authorize.searchParams.set('code_challenge_method', 's256');

  res.statusCode = 302;
  res.setHeader('location', authorize.toString());
  res.end();
}
`;

const OAUTH_CALLBACK = `// Generated by @loom/compiler. Where signing in with a provider ends (docs/17-sso.md).
import type { IncomingMessage, ServerResponse } from 'node:http';
import {
  VERIFIER_COOKIE,
  appOrigin,
  authFetch,
  clearPkceCookie,
  messageOf,
  readCookies,
  setSession,
  type AuthSession,
} from '../../src/server/auth';

/** Back to the app, saying what went wrong when something did. */
function home(req: IncomingMessage, res: ServerResponse, error?: string): void {
  const to = new URL('/', appOrigin(req));
  if (error) to.searchParams.set('auth_error', error);
  res.statusCode = 302;
  res.setHeader('location', to.toString());
  res.end();
}

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  const url = new URL(req.url ?? '/', appOrigin(req));
  const code = url.searchParams.get('code');
  const verifier = readCookies(req)[VERIFIER_COOKIE];

  // The provider says no, or the flow did not start here. Either way there is nothing to exchange.
  const denied = url.searchParams.get('error_description') ?? url.searchParams.get('error');
  if (denied) return home(req, res, denied);
  if (!code || !verifier) return home(req, res, 'That sign-in could not be completed.');

  const response = await authFetch('/token?grant_type=pkce', {
    method: 'POST',
    body: JSON.stringify({ auth_code: code, code_verifier: verifier }),
  });
  const payload = (await response.json()) as AuthSession & { error_description?: string };

  if (!response.ok || !payload.access_token) {
    // The verifier is spent either way: a failed exchange must not leave one lying around.
    res.setHeader('set-cookie', clearPkceCookie(req));
    return home(req, res, messageOf(payload, 'That sign-in was refused.'));
  }

  setSession(req, res, payload);
  res.setHeader('set-cookie', [...(res.getHeader('set-cookie') as string[]), clearPkceCookie(req)]);
  home(req, res);
}
`;

/**
 * The auth functions this project needs.
 *
 * `providers` is the closed list of sign-in providers its buttons ask for. Empty means no OAuth
 * routes at all — demand-driven like everything else, so a project with a password form ships no
 * redirect handler for a provider nobody chose.
 */
export function emitAuthFunctions(providers: readonly string[] = []): EmittedFile[] {
  const files: EmittedFile[] = [
    {
      path: AUTH_SERVER_PATH,
      content: SERVER_MODULE.replace('__PROVIDERS__', JSON.stringify([...providers])),
    },
    { path: 'api/auth/signin.ts', content: SIGN_IN },
    { path: 'api/auth/signup.ts', content: SIGN_UP },
    { path: 'api/auth/signout.ts', content: SIGN_OUT },
    { path: 'api/auth/session.ts', content: SESSION },
  ];

  if (providers.length > 0) {
    files.push(
      { path: 'api/auth/start.ts', content: OAUTH_START },
      { path: 'api/auth/callback.ts', content: OAUTH_CALLBACK },
    );
  }

  return files;
}
