import type { EmittedFile } from '../types';

/**
 * Error boundaries (L1, `docs/V1-COMPLETION.md`), compiled.
 *
 * ## What goes wrong without one
 *
 * A React component that throws while rendering takes the **whole tree** with it. Not the row, not
 * the panel — the page, replaced by nothing. One row with a date the database returned as `null`
 * and the app is a white screen with a stack trace in a console nobody is looking at.
 *
 * A forty-screen ERP that does that once is unshippable, and the failures that cause it are
 * exactly the ones a builder cannot rule out: real data has nulls, empty strings where numbers
 * were promised, and rows that arrive shaped differently from the twenty before them.
 *
 * ## Two of them, at the two places it matters
 *
 * **Per route**, so one broken screen does not take down the shell around it — the sidebar stays,
 * the navigation still works, and the person can go somewhere else.
 *
 * **Per row**, so one bad record does not blank a table of five hundred. This is the one that
 * earns its keep: the whole point of a list is that the other rows are still useful.
 *
 * ## Emitted always, not on demand
 *
 * Everything else the compiler writes is demand-driven — no charts, no chart runtime. This is
 * not, and the difference is the point: an error boundary is insurance against the thing nobody
 * predicted. "Emit it when the project needs it" would mean emitting it after the crash.
 *
 * It is about thirty lines and no dependency. `react-error-boundary` is the usual answer and it is
 * a package to carry for a class component React has supported since 16.
 */

export const BOUNDARY_MODULE_PATH = 'src/state/boundary.tsx';

export function emitBoundaryModule(): string {
  return `// Generated by @loom/compiler (docs/V1-COMPLETION.md L1).
// Managed region: edits here are overwritten on the next compile.
//
// A component that throws while rendering takes the whole tree with it unless something catches
// it. These are the two places that matters: around a screen, so one broken page does not take
// the app with it, and around a row, so one bad record does not blank the list.
import { Component, type ErrorInfo, type ReactNode } from 'react';

interface Props {
  children: ReactNode;
  /** Shown in place of whatever broke. Kept small: a row's fallback has a row's worth of space. */
  label?: string;
}

interface State {
  message: string | null;
}

/**
 * A class, because this is the one thing hooks cannot do: React has no function-component API for
 * catching a render error, and it is not an oversight — the lifecycle has to run *after* the
 * failed render.
 */
export class ErrorBoundary extends Component<Props, State> {
  state: State = { message: null };

  static getDerivedStateFromError(error: unknown): State {
    return { message: error instanceof Error ? error.message : 'Something went wrong.' };
  }

  componentDidCatch(error: unknown, info: ErrorInfo): void {
    // Logged rather than swallowed. The fallback is what the person sees; this is what whoever
    // has to fix it sees, and a boundary that hides the cause is worse than no boundary.
    console.error('Render failed', error, info.componentStack);
  }

  render(): ReactNode {
    if (this.state.message === null) return this.props.children;

    return (
      <div className="loom-error" role="alert">
        <strong>{this.props.label ?? 'This did not load.'}</strong>
        <span className="loom-error__detail">{this.state.message}</span>
      </div>
    );
  }
}
`;
}

/** The module, ready to push. One file, no dependency. */
export function emitBoundaryFile(): EmittedFile {
  return { path: BOUNDARY_MODULE_PATH, content: emitBoundaryModule() };
}
