import type { EmittedFile } from '../types';

/**
 * Running the emitted app in a container (C1, `docs/18-containers.md`).
 *
 * loom's own deploy path is Vercel, where the `api/` handlers are functions and the built front
 * end is static. A container is the other half of "the repo is yours": somewhere to run it that is
 * not a platform — a colleague's laptop, a VM, Fly, Railway, Cloud Run, a cluster.
 *
 * That needs one thing the serverless path never did: **a server**. The handlers have the shape
 * Node's http module hands you — `(req, res)` — so the server here is a router in front of them
 * and a static file server for the built app. It is emitted with the route table written out,
 * rather than scanning a directory at boot, because a route that failed to load should be a
 * compile error and not a 404 nobody can explain.
 */

const NEWLINE = String.fromCharCode(10);

/** The identifier a route's default import is bound to. */
const importName = (path: string): string =>
  `route_${path.replace(/\.ts$/, '').replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '')}`;

/**
 * The production server.
 *
 * Two jobs and a rule. It answers `/api/*` from the emitted handlers, and everything else from
 * the built front end — falling back to `index.html`, because the app routes in the browser and a
 * deep link must not 404. The rule is that a static path never leaves `dist/`: a request for
 * `../../etc/passwd` is answered with the app, not with the file.
 */
function serverModule(routes: readonly string[], uploads: readonly string[]): string {
  const imports = routes
    .map((path) => `import ${importName(path)} from './${path.replace(/\.ts$/, '')}';`)
    .join(NEWLINE);

  const table = routes
    .map((path) => `  ['/${path.replace(/^api\//, 'api/').replace(/\.ts$/, '')}', ${importName(path)}],`)
    .join(NEWLINE);

  return `// Generated by @loom/compiler. The server a container runs (docs/18-containers.md).
//
// On Vercel each file in api/ is its own function and the front end is served from the edge. In a
// container there is one process, so this is the router that stands in for both.
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { createReadStream } from 'node:fs';
import { stat } from 'node:fs/promises';
import { extname, join, normalize, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
${imports}

type Handler = (req: IncomingMessage, res: ServerResponse) => Promise<void> | void;

/** Every route this project emitted, written out rather than discovered at boot. */
const ROUTES = new Map<string, Handler>([
${table}
]);

const DIST = fileURLToPath(new URL('./dist/', import.meta.url));

const TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.avif': 'image/avif',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
};

/**
 * The file a request asks for, or nothing when it asks for something outside the built app.
 *
 * The check is on the *resolved* path, not on the text of the request: '..' segments, an encoded
 * separator and a symlinked name all end up somewhere, and where they end up is the only thing
 * worth testing.
 */
function fileFor(pathname: string): string | undefined {
  const wanted = resolve(join(DIST, normalize(decodeURIComponent(pathname))));
  if (wanted !== DIST.replace(/[\\\\/]$/, '') && !wanted.startsWith(DIST.endsWith(sep) ? DIST : DIST + sep)) {
    return undefined;
  }
  return wanted;
}

async function sendFile(res: ServerResponse, path: string): Promise<boolean> {
  try {
    const info = await stat(path);
    if (!info.isFile()) return false;

    res.statusCode = 200;
    res.setHeader('content-type', TYPES[extname(path).toLowerCase()] ?? 'application/octet-stream');
    // The built assets carry a content hash in their names, so they can be cached forever; the
    // HTML that names them cannot be, or a deploy would never be seen.
    res.setHeader(
      'cache-control',
      path.includes(\`\${sep}assets\${sep}\`) ? 'public, max-age=31536000, immutable' : 'no-cache',
    );
    await new Promise<void>((done, fail) => {
      createReadStream(path).on('error', fail).on('end', done).pipe(res);
    });
    return true;
  } catch {
    return false;
  }
}

${
    uploads.length > 0
      ? `/**
 * Files uploaded to local disk (docs/29-storage.md).
 *
 * Served from the folder the bucket writes to, with the same resolved-path check the built assets
 * get: a key that climbs out of the folder is refused, whatever it looks like before it resolves.
 * On a serverless host this folder does not survive between invocations, which is why local disk is
 * for a laptop or a container with a volume.
 */
const UPLOADS = ${JSON.stringify(uploads)}.map((folder) => resolve(folder));

function uploadFor(pathname: string): string | undefined {
  const key = normalize(decodeURIComponent(pathname.slice('/files/'.length)));
  for (const root of UPLOADS) {
    const wanted = resolve(join(root, key));
    if (wanted === root || wanted.startsWith(root + sep)) return wanted;
  }
  return undefined;
}

`
      : ''
}const server = createServer((req, res) => {
  void (async () => {
    const url = new URL(req.url ?? '/', 'http://localhost');
    const handler = ROUTES.get(url.pathname.replace(/\\/+$/, '') || '/');

    if (handler) {
      try {
        await handler(req, res);
      } catch (error) {
        res.statusCode = 500;
        res.setHeader('content-type', 'application/json');
        res.end(JSON.stringify({ error: error instanceof Error ? error.message : 'Failed.' }));
      }
      return;
    }

${
    uploads.length > 0
      ? `    if (url.pathname.startsWith('/files/')) {
      const stored = uploadFor(url.pathname);
      if (stored && (await sendFile(res, stored))) return;
      res.statusCode = 404;
      res.end('Not found');
      return;
    }

`
      : ''
}    if (url.pathname.startsWith('/api/')) {
      res.statusCode = 404;
      res.setHeader('content-type', 'application/json');
      res.end(JSON.stringify({ error: 'No such route.' }));
      return;
    }

    const asked = fileFor(url.pathname);
    if (asked && (await sendFile(res, asked))) return;

    // Anything else is a screen: the app routes in the browser, so a deep link gets the app.
    if (await sendFile(res, join(DIST, 'index.html'))) return;

    res.statusCode = 404;
    res.end('Not found');
  })();
});

const port = Number(process.env.PORT ?? 3000);
server.listen(port, () => {
  console.log(\`Listening on http://localhost:\${port}\`);
});
`;
}

/**
 * The Dockerfile.
 *
 * Two stages, so the image that runs is not the image that compiled. The build stage installs
 * everything and runs the project's own `build` — the same `tsc --noEmit && vite build` a
 * developer runs — and the runtime stage installs production dependencies only.
 *
 * The server is started with `tsx` rather than compiled to JavaScript first: the emitted handlers
 * import each other without file extensions, which Node's ESM loader requires and TypeScript's
 * `nodenext` output would have to be rewritten to add. Running the TypeScript directly is the
 * honest version of that, and it is one dependency rather than a second build config.
 */
function dockerfile(hasRoutes: boolean): string {
  // `COPY` fails on a source that is not there, and a project with no API routes has no `api/`.
  // Docker has no conditional, so the line is written only when there is something to copy —
  // which is also why this is a function and not a constant.
  const api = hasRoutes ? 'COPY --from=build /app/api ./api' + NEWLINE : '';

  return `# Generated by @loom/compiler (docs/18-containers.md).
# syntax=docker/dockerfile:1

FROM node:22-alpine AS build
WORKDIR /app

# Dependencies first, so a change to the app does not reinstall them.
COPY package.json package-lock.json* ./
RUN npm install --no-audit --no-fund

COPY . .
# The project's own build: tsc --noEmit && vite build. A type error stops the image here rather
# than at run time.
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json* ./
RUN npm install --omit=dev --no-audit --no-fund

# Only what runs: the built front end, the sources the handlers import, and the server in front
# of them.
COPY --from=build /app/dist ./dist
COPY --from=build /app/src ./src
${api}COPY --from=build /app/server.ts ./server.ts

# Not root. A process that never needs to write to its own image should not be able to.
USER node

EXPOSE 3000
CMD ["npm", "run", "start"]
`;
}

const DOCKERIGNORE = `# Generated by @loom/compiler.
node_modules
dist
.env
.env.*
!.env.example
.git
.DS_Store
npm-debug.log*
`;

/**
 * Compose: the app, and a database when the project talks to one directly.
 *
 * The point of the database service is the *first* run — a project whose schema exists only as
 * migrations has somewhere to apply them without anyone signing up for anything. A project on
 * Supabase or Firestore reaches a service that is already running, so compose only carries the app
 * and hands it the names it reads.
 */
function compose(
  usesSql: boolean,
  credentials: readonly string[],
  gotrueProviders: readonly string[] = [],
): string {
  const environment = credentials
    .map((name) => `      ${name}: \${${name}}`)
    .join(NEWLINE);

  const database = `
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-loom}
      POSTGRES_DB: \${POSTGRES_DB:-app}
    volumes:
      - db:/var/lib/postgresql/data
    # The app waits for a database that answers, not merely one that has started.
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db:
`;

  /**
   * The auth server, for a project that runs its own (`docs/20-provider-setup.md`).
   *
   * Every provider's id and secret arrives as an environment variable **by name**, exactly as
   * GoTrue reads them. No value is ever written here: this file is committed, and the values are
   * not loom's to hold.
   */
  const authService =
    gotrueProviders.length > 0
      ? `
  auth:
    image: supabase/gotrue:v2.176.1
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: \${DATABASE_URL}
      GOTRUE_JWT_SECRET: \${GOTRUE_JWT_SECRET}
      GOTRUE_SITE_URL: \${SITE_URL:-http://localhost:3000}
      GOTRUE_URI_ALLOW_LIST: \${SITE_URL:-http://localhost:3000}/*
      API_EXTERNAL_URL: \${AUTH_URL:-http://localhost:9999}
${gotrueProviders
  .map((provider) => {
    const upper = provider.toUpperCase();
    return [
      `      GOTRUE_EXTERNAL_${upper}_ENABLED: 'true'`,
      `      GOTRUE_EXTERNAL_${upper}_CLIENT_ID: \${GOTRUE_EXTERNAL_${upper}_CLIENT_ID}`,
      `      GOTRUE_EXTERNAL_${upper}_SECRET: \${GOTRUE_EXTERNAL_${upper}_SECRET}`,
      `      GOTRUE_EXTERNAL_${upper}_REDIRECT_URI: \${AUTH_URL:-http://localhost:9999}/callback`,
    ].join(NEWLINE);
  })
  .join(NEWLINE)}
    ports:
      - '9999:9999'
`
      : '';

  return `# Generated by @loom/compiler (docs/18-containers.md).
services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - '\${PORT:-3000}:3000'
    # Read by NAME from the environment, never written into this file: values live in .env, which
    # is git-ignored, or in whatever the host injects (docs/05-guardrails.md #1).
    env_file:
      - path: .env
        required: false
    environment:
${environment || '      NODE_ENV: production'}${
    usesSql
      ? `
    depends_on:
      db:
        condition: service_healthy`
      : ''
  }
${authService}${usesSql || authService ? database : ''}`;
}

export interface ContainerOptions {
  /** Folders a local-disk bucket writes into, served back at /files (`docs/29-storage.md`). */
  uploadFolders?: readonly string[];
  /**
   * Sign-in providers whose secrets this project supplies itself (A3).
   *
   * Only for a project running its **own** auth server: on hosted Supabase these variables are
   * read by nothing, and writing them into an example file would be telling someone to set
   * something that has no effect.
   */
  gotrueProviders?: readonly string[];
  /** Every emitted `api/**.ts` path, which becomes the route table. */
  routes: readonly string[];
  /** Whether the project talks to a database directly, and so gets one in compose. */
  usesSql: boolean;
  /** Credential names this project reads, so compose passes exactly those through. */
  credentials: readonly string[];
}

export function emitContainerFiles(options: ContainerOptions): EmittedFile[] {
  return [
    { path: 'server.ts', content: serverModule([...options.routes].sort(), options.uploadFolders ?? []) },
    { path: 'Dockerfile', content: dockerfile(options.routes.length > 0) },
    { path: '.dockerignore', content: DOCKERIGNORE },
    {
      path: 'docker-compose.yml',
      content: compose(
        options.usesSql,
        [...options.credentials].sort(),
        options.gotrueProviders ?? [],
      ),
    },
  ];
}
