import type { EmittedFile } from '../types';
import type { BucketPlan } from './storage';

/**
 * File operations as nodes (N3, `docs/V1-COMPLETION.md` §10), compiled.
 *
 * ## The hole this closes
 *
 * Five bucket providers ship — local disk, R2, S3, Supabase Storage, Firebase Storage — and until
 * now the canvas could reach exactly none of them. An upload field could put a file somewhere and
 * nothing could ever list it, delete it, or hand somebody a link to it. A connector with no node
 * is a connector nobody has.
 *
 * ## Server-side, without exception
 *
 * The same rule the whole storage design turns on: **a bucket credential in a browser is a bucket
 * anyone can write to** (`docs/29-storage.md`). It is in the bundle, it is in the network tab, and
 * it does not expire. So these are steps inside an API route, like a database write, and the
 * compiler refuses them anywhere else.
 *
 * The upload *field* keeps its three-step signed path, which exists precisely so a browser can put
 * a file somewhere without ever holding a key. These are for everything a project needs to do to a
 * file that is not a person choosing one.
 *
 * ## Only what the project attached
 *
 * A project with one local-disk bucket gets the local-disk branch and nothing else — no S3 client,
 * no Supabase client, no Firebase admin. Same demand-driven rule the signer follows, and the same
 * reason: an SDK imported for a provider nobody uses is weight in every cold start.
 */

export const FILES_MODULE_PATH = 'src/server/files.ts';

/** The four things a project needs to do to a file it did not just receive. */
export const FILE_KINDS = ['listFiles', 'deleteFile', 'signUrl', 'putFile'] as const;
export type FileKind = (typeof FILE_KINDS)[number];

/** Providers these operations are implemented for. */
const SUPPORTED = new Set(['local', 's3', 'r2', 'supabase-storage', 'firebase-storage']);

export function supportsFileOps(moduleId: string): boolean {
  return SUPPORTED.has(moduleId);
}

/**
 * The module the file nodes call.
 *
 * One dispatch per operation rather than one client per operation: the bucket a step names decides
 * which provider answers, and the step itself never knows which it was. That is what lets a
 * project move a bucket from local disk to R2 without touching the graph.
 */
export function emitFilesModule(plans: readonly BucketPlan[]): string {
  const modules = new Set(plans.map((plan) => plan.moduleId));
  const has = (id: string): boolean => modules.has(id);
  const s3ish = has('s3') || has('r2');

  const imports: string[] = [];
  if (has('local')) {
    imports.push(
      `import { mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';`,
      `import { dirname, join } from 'node:path';`,
    );
  }
  if (s3ish) {
    imports.push(
      `import {`,
      `  DeleteObjectCommand,`,
      `  GetObjectCommand,`,
      `  ListObjectsV2Command,`,
      `  PutObjectCommand,`,
      `  S3Client,`,
      `} from '@aws-sdk/client-s3';`,
      `import { getSignedUrl } from '@aws-sdk/s3-request-presigner';`,
    );
  }
  if (has('supabase-storage'))
    imports.push(`import { createClient } from '@supabase/supabase-js';`);
  if (has('firebase-storage')) {
    imports.push(
      `import { cert, getApps, initializeApp } from 'firebase-admin/app';`,
      `import { getStorage } from 'firebase-admin/storage';`,
    );
  }

  const branches = (build: (id: string) => string[]): string =>
    [...modules]
      .filter((id) => SUPPORTED.has(id))
      .flatMap((id) => build(id))
      .join('\n');

  return `// Generated by @loom/compiler (docs/V1-COMPLETION.md N3).
// Managed region: edits here are overwritten on the next compile.
//
// What a project does to a file it did not just receive: list one, remove one, hand somebody a
// link to one, write one. Server-side only — a bucket credential in a browser is a bucket anyone
// can write to, which is the rule the whole storage design turns on (docs/29-storage.md).
import { BUCKETS, safeFileName, storageKey, type BucketSettings } from './buckets';
${imports.join('\n')}

export interface StoredFile {
  key: string;
  size: number;
  /** ISO 8601, or empty where the provider does not say. */
  updatedAt: string;
  contentType: string;
}
${
  modules.size === 1 && has('local')
    ? ''
    : `
/** Half a minute at least, a week at most. A link with no ceiling is a public link. */
function ttlOf(seconds: number): number {
  return Math.min(Math.max(30, Math.trunc(seconds)), 60 * 60 * 24 * 7);
}
`
}

/** The bucket a step named, or a refusal that says which one is missing. */
function bucketOf(bucketId: string): BucketSettings {
  const settings = BUCKETS[bucketId];
  if (!settings) throw new Error('There is no bucket called "' + bucketId + '".');
  return settings;
}

${
  modules.size === 1 && has('local')
    ? ''
    : `
function required(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error('Missing ' + name + '.');
  return value;
}
`
}${
    has('local')
      ? `
/** Where a local bucket keeps its files, and never above it. */
function localPath(settings: BucketSettings, key: string): string {
  const root = join(process.cwd(), settings.directory || '.data/uploads');
  const full = join(root, key);
  // A key is text that came from somewhere. Anything that climbs out of the folder is refused
  // here rather than trusted to have been cleaned earlier.
  if (!full.startsWith(root)) throw new Error('That file is not in this bucket.');
  return full;
}
`
      : ''
  }${
    s3ish
      ? `
function s3For(settings: BucketSettings): S3Client {
  const isR2 = settings.module === 'r2';
  return new S3Client({
    region: isR2 ? 'auto' : settings.region || 'us-east-1',
    ...(isR2
      ? { endpoint: 'https://' + required('R2_ACCOUNT_ID') + '.r2.cloudflarestorage.com' }
      : {}),
    credentials: {
      accessKeyId: required(isR2 ? 'R2_ACCESS_KEY_ID' : 'AWS_ACCESS_KEY_ID'),
      secretAccessKey: required(isR2 ? 'R2_SECRET_ACCESS_KEY' : 'AWS_SECRET_ACCESS_KEY'),
    },
  });
}
`
      : ''
  }${
    has('supabase-storage')
      ? `
function supabaseFor(): ReturnType<typeof createClient> {
  return createClient(required('SUPABASE_URL'), required('SUPABASE_SERVICE_ROLE_KEY'));
}
`
      : ''
  }${
    has('firebase-storage')
      ? `
function firebaseBucket(settings: BucketSettings) {
  if (getApps().length === 0) {
    initializeApp({ credential: cert(JSON.parse(required('FIREBASE_SERVICE_ACCOUNT'))) });
  }
  return getStorage().bucket(settings.bucket);
}
`
      : ''
  }
/**
 * What is in a bucket.
 *
 * Capped, because "list a bucket" is a request that can answer with a hundred thousand rows and a
 * step that does that is a step that times out.
 */
export async function listFiles(bucketId: string, prefix = '', limit = 100): Promise<StoredFile[]> {
  const settings = bucketOf(bucketId);
  const cap = Math.min(Math.max(1, Math.trunc(limit)), 1000);
  const under = (settings.prefix ? settings.prefix.replace(/^\\/+|\\/+$/g, '') + '/' : '') + prefix;

${branches((id) => [listBranch(id)])}
  throw new Error('Listing is not supported for this bucket.');
}

/** Remove one. */
export async function deleteFile(bucketId: string, key: string): Promise<void> {
  const settings = bucketOf(bucketId);
  if (!key) throw new Error('Which file?');

${branches((id) => [deleteBranch(id)])}
  throw new Error('Deleting is not supported for this bucket.');
}

/**
 * A link to one, good for a while.
 *
 * Signed rather than public: a bucket that is readable by anyone with the address is a bucket
 * whose addresses are guessable, and "unlisted" is not a permission.
 */
export async function signUrl(bucketId: string, key: string, seconds = 300): Promise<string> {
  const settings = bucketOf(bucketId);
  if (!key) throw new Error('Which file?');

${branches((id) => [signBranch(id)])}
  throw new Error('Signing is not supported for this bucket.');
}

/**
 * Write one from the server.
 *
 * Not the path a person's upload takes — that is the signed ticket, which exists so a browser can
 * put a file somewhere without ever holding a key. This is for a file the *server* made: a
 * generated report, a fetched image, an export.
 */
export async function putFile(
  bucketId: string,
  name: string,
  body: string | Uint8Array,
  contentType = 'application/octet-stream',
): Promise<StoredFile> {
  const settings = bucketOf(bucketId);
  const key = storageKey(settings, safeFileName(name));
  const bytes = typeof body === 'string' ? new TextEncoder().encode(body) : body;

${branches((id) => [putBranch(id)])}
  throw new Error('Writing is not supported for this bucket.');
}
`;
}

/* ---- the per-provider bodies ------------------------------------------------------------- */

const guard = (id: string): string => `  if (settings.module === ${JSON.stringify(id)}) {`;

function listBranch(id: string): string {
  if (id === 'local') {
    return `${guard(id)}
    const root = localPath(settings, '');
    const names = await readdir(root).catch(() => [] as string[]);
    const found: StoredFile[] = [];
    for (const name of names) {
      if (under && !name.startsWith(under)) continue;
      const info = await stat(join(root, name)).catch(() => undefined);
      if (!info?.isFile()) continue;
      found.push({
        key: name,
        size: info.size,
        updatedAt: info.mtime.toISOString(),
        // The disk does not record one, and guessing from the extension would be a guess.
        contentType: '',
      });
      if (found.length >= cap) break;
    }
    return found;
  }`;
  }

  if (id === 's3' || id === 'r2') {
    return `${guard(id)}
    const answer = await s3For(settings).send(
      new ListObjectsV2Command({ Bucket: settings.bucket, Prefix: under, MaxKeys: cap }),
    );
    return (answer.Contents ?? []).map((entry) => ({
      key: String(entry.Key ?? ''),
      size: Number(entry.Size ?? 0),
      updatedAt: entry.LastModified ? entry.LastModified.toISOString() : '',
      contentType: '',
    }));
  }`;
  }

  if (id === 'supabase-storage') {
    return `${guard(id)}
    const { data, error } = await supabaseFor()
      .storage.from(settings.bucket)
      .list(under || undefined, { limit: cap });
    if (error) throw new Error(error.message);
    return (data ?? []).map((entry) => ({
      key: (under ? under.replace(/\\/*$/, '/') : '') + entry.name,
      size: Number((entry.metadata as { size?: number } | null)?.size ?? 0),
      updatedAt: String(entry.updated_at ?? ''),
      contentType: String((entry.metadata as { mimetype?: string } | null)?.mimetype ?? ''),
    }));
  }`;
  }

  return `${guard(id)}
    const [found] = await firebaseBucket(settings).getFiles({ prefix: under, maxResults: cap });
    return found.map((entry) => ({
      key: entry.name,
      size: Number(entry.metadata.size ?? 0),
      updatedAt: String(entry.metadata.updated ?? ''),
      contentType: String(entry.metadata.contentType ?? ''),
    }));
  }`;
}

function deleteBranch(id: string): string {
  if (id === 'local') {
    return `${guard(id)}
    // \`force\` so removing something already gone is not an error: the end state is what was asked
    // for either way, and a delete that fails because it succeeded earlier is noise.
    await rm(localPath(settings, key), { force: true });
    return;
  }`;
  }

  if (id === 's3' || id === 'r2') {
    return `${guard(id)}
    await s3For(settings).send(new DeleteObjectCommand({ Bucket: settings.bucket, Key: key }));
    return;
  }`;
  }

  if (id === 'supabase-storage') {
    return `${guard(id)}
    const { error } = await supabaseFor().storage.from(settings.bucket).remove([key]);
    if (error) throw new Error(error.message);
    return;
  }`;
  }

  return `${guard(id)}
    await firebaseBucket(settings).file(key).delete({ ignoreNotFound: true });
    return;
  }`;
}

function signBranch(id: string): string {
  if (id === 'local') {
    return `${guard(id)}
    /**
     * A local bucket is served by this app, so the link is a path into it. There is no third party
     * to sign for — the app is the one deciding whether to answer, on every request.
     *
     * Which is why the expiry is not honoured here rather than being pretended at: a URL carrying
     * an "expires" that nothing checks is worse than one that never claimed to have one.
     */
    void seconds;
    return '/files/' + key;
  }`;
  }

  if (id === 's3' || id === 'r2') {
    return `${guard(id)}
    return getSignedUrl(
      s3For(settings),
      new GetObjectCommand({ Bucket: settings.bucket, Key: key }),
      { expiresIn: ttlOf(seconds) },
    );
  }`;
  }

  if (id === 'supabase-storage') {
    return `${guard(id)}
    const { data, error } = await supabaseFor()
      .storage.from(settings.bucket)
      .createSignedUrl(key, ttlOf(seconds));
    if (error || !data) throw new Error(error?.message ?? 'Could not sign that link.');
    return data.signedUrl;
  }`;
  }

  return `${guard(id)}
    const [url] = await firebaseBucket(settings)
      .file(key)
      .getSignedUrl({ action: 'read', expires: Date.now() + ttlOf(seconds) * 1000 });
    return url;
  }`;
}

function putBranch(id: string): string {
  if (id === 'local') {
    return `${guard(id)}
    const full = localPath(settings, key);
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, bytes);
    return { key, size: bytes.byteLength, updatedAt: new Date().toISOString(), contentType };
  }`;
  }

  if (id === 's3' || id === 'r2') {
    return `${guard(id)}
    await s3For(settings).send(
      new PutObjectCommand({
        Bucket: settings.bucket,
        Key: key,
        Body: bytes,
        ContentType: contentType,
      }),
    );
    return { key, size: bytes.byteLength, updatedAt: new Date().toISOString(), contentType };
  }`;
  }

  if (id === 'supabase-storage') {
    return `${guard(id)}
    const { error } = await supabaseFor()
      .storage.from(settings.bucket)
      .upload(key, bytes, { contentType, upsert: true });
    if (error) throw new Error(error.message);
    return { key, size: bytes.byteLength, updatedAt: new Date().toISOString(), contentType };
  }`;
  }

  return `${guard(id)}
    await firebaseBucket(settings)
      .file(key)
      .save(Buffer.from(bytes), { contentType });
    return { key, size: bytes.byteLength, updatedAt: new Date().toISOString(), contentType };
  }`;
}

/** The module, when the project has any bucket at all. */
export function emitFilesFile(plans: readonly BucketPlan[]): EmittedFile[] {
  if (plans.length === 0) return [];
  return [{ path: FILES_MODULE_PATH, content: emitFilesModule(plans) }];
}
