import { tsTypeOf } from '@loom/typesys';
import type { GlobalPlan } from './state';

/**
 * The app's global variables, emitted as one React context above the router.
 *
 * A screen variable is a `useState` inside one artboard's module; a global has to outlive the
 * screen that wrote it, so it lives one level up — exactly what the glossary says a global bucket
 * is (`docs/06-glossary.md`: "app-wide data → app store/Context"). Context is also what a
 * developer would have written here: no store library, no subscription graph, nothing shipped
 * with the app that a person opening the repo would not recognise.
 *
 * The provider holds one `useState` per variable, and hands both halves down. Screens destructure
 * only the ones they touch, so a screen that reads nothing global imports nothing.
 */
export const GLOBALS_MODULE_PATH = 'src/state/globals.tsx';

export function emitGlobalsModule(globals: GlobalPlan[]): string {
  const members = globals
    .map(
      (global) =>
        `  /** "${global.key}" — set from any screen, read from any screen. */\n` +
        `  ${global.member}: ${tsTypeOf(global.type)} | null;\n` +
        `  set_${global.member}: (value: ${tsTypeOf(global.type)} | null) => void;`,
    )
    .join('\n');

  const declarations = globals
    .map(
      (global) =>
        `  const [${global.member}, set_${global.member}] = useState<${tsTypeOf(global.type)} | null>(null);`,
    )
    .join('\n');

  const value = globals
    .map((global) => `${global.member}, set_${global.member}`)
    .join(', ');

  return `// Generated by @loom/compiler. The app's global variables — one value per name, shared by
// every screen. Managed region: edits here are overwritten on the next compile.
import { createContext, useContext, useState, type ReactNode } from 'react';

export interface Globals {
${members}
}

const GlobalsContext = createContext<Globals | null>(null);

export function GlobalsProvider({ children }: { children: ReactNode }) {
${declarations}
  return (
    <GlobalsContext.Provider value={{ ${value} }}>{children}</GlobalsContext.Provider>
  );
}

export function useGlobals(): Globals {
  const globals = useContext(GlobalsContext);
  if (!globals) throw new Error('useGlobals was called outside <GlobalsProvider>.');
  return globals;
}
`;
}
