import { actionsOf, type Snapshot } from '@loom/ir';
import { tokenVar } from '@loom/ui';

/**
 * The message toast, emitted as one host above the router.
 *
 * It started inside the screen's own module, and that was wrong for the sequence the whole feature
 * exists to serve: "save, confirm, **navigate**" unmounts the screen — and its toast with it — a
 * frame after the confirmation appears. A message outlives the screen that sent it, so it lives
 * one level up, exactly like a global variable (`emit/globals.ts`).
 *
 * Context, a `useState` and a `setTimeout`: real code the person owns, no library, nothing a
 * developer opening the repo would not recognise.
 */

export const MESSAGES_MODULE_PATH = 'src/state/messages.tsx';
export const MESSAGE_FN = 'showMessage';

/** Does anything in the project show a message? Nothing is emitted if not. */
export function usesMessages(snapshot: Snapshot): boolean {
  for (const component of Object.values(snapshot.components)) {
    for (const value of Object.values(component.props)) {
      if (value.kind !== 'event') continue;
      if (actionsOf(value.handler).some((action) => action.kind === 'message')) return true;
    }
  }
  return false;
}

export function emitMessagesModule(): string {
  return `// Generated by @loom/compiler. The app's message toast — one host, above the router, so a
// message outlives the screen that sent it. Managed region: edits here are overwritten.
import { createContext, useCallback, useContext, useEffect, useState, type ReactNode } from 'react';

export interface LoomMessage {
  text: string;
  tone: 'ok' | 'error';
}

export interface Messages {
  ${MESSAGE_FN}: (message: LoomMessage) => void;
}

const MessagesContext = createContext<Messages | null>(null);

export function MessagesProvider({ children }: { children: ReactNode }) {
  const [message, setMessage] = useState<LoomMessage | null>(null);
  const ${MESSAGE_FN} = useCallback((next: LoomMessage) => setMessage(next), []);

  // It clears itself; nothing in the app has to dismiss it.
  useEffect(() => {
    if (!message) return;
    const timer = setTimeout(() => setMessage(null), 3000);
    return () => clearTimeout(timer);
  }, [message]);

  return (
    <MessagesContext.Provider value={{ ${MESSAGE_FN} }}>
      {children}
      {message ? (
        <div
          role="status"
          style={{
            position: 'fixed',
            left: '50%',
            bottom: 24,
            transform: 'translateX(-50%)',
            padding: '10px 16px',
            borderRadius: '${tokenVar('radius.md')}',
            color: '${tokenVar('color.surface')}',
            background:
              message.tone === 'error' ? '${tokenVar('color.danger')}' : '${tokenVar('color.ink')}',
          }}
        >
          {message.text}
        </div>
      ) : null}
    </MessagesContext.Provider>
  );
}

export function useMessages(): Messages {
  const messages = useContext(MessagesContext);
  if (!messages) throw new Error('useMessages was called outside <MessagesProvider>.');
  return messages;
}
`;
}
