import type { Artboard, Snapshot } from '@loom/ir';
import type { RouteInfo, RouteMap } from './routes';

/**
 * Public pages (L4, `docs/V1-COMPLETION.md`), compiled.
 *
 * ## The problem, stated plainly
 *
 * A Vite SPA serves one `index.html` with an empty `<div id="root">`. A crawler that fetches a
 * product page gets that empty div, and a marketing site whose pages return no words is not a
 * marketing site. Everything about the app is right except the first response.
 *
 * ## Why this is not a Next.js target
 *
 * The obvious fix is a framework that renders on the server, and `03-system-memory.md` deferred
 * that deliberately: a second emitter target doubles the compiler, and every node type would then
 * need an answer for the server/client boundary. That is a large, permanent cost for a problem
 * that only affects pages a stranger can see.
 *
 * So: **prerender at build time.** After `vite build`, the same React tree is rendered once per
 * public route with `renderToString`, and the HTML is written into the file the crawler will get.
 * The app still hydrates and behaves exactly as it did. Nothing about the runtime changes.
 *
 * ## What it costs: nothing, in dependencies
 *
 * `react-dom/server` ships inside `react-dom`, and `StaticRouter` inside `react-router-dom`. Both
 * are already there. The prerender is a Vite SSR build — which Vite does natively — plus a script.
 * No framework, no plugin, no new package.
 *
 * ## What it cannot do, and says so
 *
 * A route with a param (`/invoice/:id`) has no fixed content to render: there is one page per
 * record and the build does not know the records. Those stay client-rendered, and marking one
 * public raises a Problem rather than quietly emitting a page about nothing.
 */

/** Absent means private, because the safe default for "should a stranger see this" is no. */
export function isPublic(artboard: Artboard): boolean {
  return artboard.public === true;
}

/**
 * The routes worth prerendering: public, and static.
 *
 * A guarded screen is never prerendered even if someone marks it public — the guard exists because
 * the content is for a particular person, and writing it into a file anyone can fetch would turn a
 * router-level convenience into a disclosure.
 */
export function prerenderable(snapshot: Snapshot, routes: RouteMap): RouteInfo[] {
  const out: RouteInfo[] = [];
  for (const artboard of Object.values(snapshot.artboards)) {
    if (!isPublic(artboard) || artboard.guard) continue;
    if ((artboard.params ?? []).length > 0) continue;
    const route = routes.get(artboard.id);
    if (route) out.push(route);
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

export function hasPublicPages(snapshot: Snapshot, routes: RouteMap): boolean {
  return prerenderable(snapshot, routes).length > 0;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * The `<head>` a route carries.
 *
 * Open Graph and Twitter tags alongside the standard ones, because "share this link" is the other
 * half of what a public page is for, and the card is what people actually see.
 */
export function metaTags(artboard: Artboard, fallbackTitle: string): string {
  const meta = artboard.meta ?? {};
  const title = meta.title ?? `${artboard.name} — ${fallbackTitle}`;
  const tags = [
    `<title>${escapeHtml(title)}</title>`,
    `<meta property="og:title" content="${escapeHtml(title)}" />`,
  ];

  if (meta.description) {
    tags.push(
      `<meta name="description" content="${escapeHtml(meta.description)}" />`,
      `<meta property="og:description" content="${escapeHtml(meta.description)}" />`,
    );
  }
  if (meta.image) {
    tags.push(
      `<meta property="og:image" content="${escapeHtml(meta.image)}" />`,
      `<meta name="twitter:card" content="summary_large_image" />`,
    );
  }
  tags.push(`<meta property="og:type" content="website" />`);
  return tags.join('\n    ');
}

export const APP_ROUTES_PATH = 'src/AppRoutes.tsx';
export const ENTRY_SERVER_PATH = 'src/entry-server.tsx';
export const PRERENDER_SCRIPT_PATH = 'scripts/prerender.mjs';

/**
 * The server entry: the same `App`, rendered to a string at a given URL.
 *
 * `StaticRouter` rather than `BrowserRouter` because there is no history at build time — the URL
 * is handed in. Everything else about the tree is identical, which is the point: there is one app,
 * rendered twice, not two apps to keep in agreement.
 */
export function entryServerSource(): string {
  return `// Generated by @loom/compiler. Used only by the build's prerender step.
// Managed region: edits here are overwritten on the next compile.
import { StaticRouter } from 'react-router-dom/server';
import { renderToString } from 'react-dom/server';
import AppRoutes from './AppRoutes';

/**
 * Render one route to HTML.
 *
 * The app mounts \`BrowserRouter\` in \`App\`; here the router is supplied instead, so the same
 * component tree renders against a URL the build knows rather than one a browser is at.
 */
export function render(url: string): string {
  return renderToString(
    <StaticRouter location={url}>
      <AppRoutes />
    </StaticRouter>,
  );
}
`;
}

/**
 * The build step.
 *
 * Written as plain ESM run by Node, not as a Vite plugin: it is fifty lines of file writing, and a
 * plugin would be a lifecycle to learn for no benefit. Someone opening the repo can read it.
 */
export function prerenderScript(routes: RouteInfo[], heads: Record<string, string>): string {
  const manifest = routes.map((route) => ({ path: route.path, head: heads[route.path] ?? '' }));

  return `// Generated by @loom/compiler (docs/V1-COMPLETION.md L4).
// Managed region: edits here are overwritten on the next compile.
//
// Runs after \`vite build\`. Renders each public route to HTML and writes it where a crawler —
// and a person on a slow connection — will get words instead of an empty div. The app still
// hydrates over it and behaves exactly as before.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

/** Set at build time so the sitemap can carry absolute URLs, which the spec requires. */
const SITE_URL = (process.env.SITE_URL ?? '').replace(/\\/$/, '');

const ROUTES = ${JSON.stringify(manifest, null, 2)};

const dist = join(process.cwd(), 'dist');
const template = await readFile(join(dist, 'index.html'), 'utf8');
// A file:// URL, not the bare path. Node's ESM loader rejects a Windows absolute path outright:
// it reads the drive letter as a URL scheme it does not recognise, and refuses to load anything.
const { render } = await import(
  pathToFileURL(join(process.cwd(), 'dist-server', 'entry-server.js')).href
);

for (const route of ROUTES) {
  const html = render(route.path);

  const page = template
    // The head this route declares replaces the shell's default title.
    .replace(/<title>[\\s\\S]*?<\\/title>/, route.head)
    .replace('<div id="root"></div>', \`<div id="root">\${html}</div>\`);

  // \`/\` becomes \`index.html\`; \`/pricing\` becomes \`pricing/index.html\`, so a static host serves
  // it at the address it was designed at without a rewrite rule.
  const file = route.path === '/' ? 'index.html' : join(route.path.slice(1), 'index.html');
  const target = join(dist, file);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, page, 'utf8');
  console.log('prerendered', route.path);
}

if (SITE_URL) {
  const urls = ROUTES.map(
    (route) => \`  <url><loc>\${SITE_URL}\${route.path === '/' ? '' : route.path}</loc></url>\`,
  ).join('\\n');
  await writeFile(
    join(dist, 'sitemap.xml'),
    \`<?xml version="1.0" encoding="UTF-8"?>\\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\\n\${urls}\\n</urlset>\\n\`,
    'utf8',
  );
  await writeFile(
    join(dist, 'robots.txt'),
    \`User-agent: *\\nAllow: /\\nSitemap: \${SITE_URL}/sitemap.xml\\n\`,
    'utf8',
  );
} else {
  // Said out loud rather than guessed at: a sitemap needs absolute URLs, and nothing in the
  // project knows the domain it will be served from.
  await writeFile(join(dist, 'robots.txt'), 'User-agent: *\\nAllow: /\\n', 'utf8');
  console.warn('SITE_URL is not set, so no sitemap.xml was written.');
}
`;
}

/** The build command, once a project has anything public to prerender. */
export const PRERENDER_BUILD = `tsc --noEmit && vite build && vite build --ssr ${ENTRY_SERVER_PATH} --outDir dist-server && node ${PRERENDER_SCRIPT_PATH}`;
