/**
 * The variant stylesheet: modern defaults for every element (`docs/27-variants.md`).
 *
 * An element used to arrive as the browser's default — a grey square button, a hairline input —
 * so every project began by hand-styling the same six properties on every element, and two
 * designers on the same project styled them differently. Shadcn and MUI answer this the same way,
 * and the answer is right: a small set of **named variants**, one of them the default.
 *
 * **These bytes are emitted into the project and injected into the studio's canvas.** Not a copy
 * of each — the same string. A canvas that disagrees with the running app is a canvas nobody can
 * design in, and two stylesheets meaning to say the same thing eventually do not.
 *
 * Everything is written in the project's own tokens. No hex codes: a project that moves
 * `color.brand` moves every solid button with it, which is the whole reason tokens exist.
 *
 * Specificity stays at one class deliberately. A component's own style block emits *inline*, and
 * inline always wins — variants are the floor, never the ceiling.
 */

/** The namespace every class carries, so a project's own CSS can never collide with it. */
export const CLASS_PREFIX = 'loom';

const HEADER = `/*
 * Generated by loom from the design system (docs/27-variants.md).
 *
 * Every value here is one of the project's own tokens, so restyling is a change in theme.css
 * rather than a sweep through this file. Edits here are overwritten on the next compile — if you
 * have taken the repo and stopped regenerating, it is yours like everything else.
 */`;

const BUTTON = `
/* ---- Button ---------------------------------------------------------------------------- */

.loom-button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--loom-space-2);
  box-sizing: border-box;
  font-family: var(--loom-font-body);
  font-weight: var(--loom-weight-medium);
  line-height: 1;
  text-decoration: none;
  white-space: nowrap;
  border: 1px solid transparent;
  border-radius: var(--loom-radius-md);
  cursor: pointer;
  transition:
    background-color 120ms ease,
    border-color 120ms ease,
    color 120ms ease,
    box-shadow 120ms ease;
}

/* Never removed, only replaced: a control invisible to a keyboard is a control some people cannot
   use at all. */
.loom-button:focus-visible {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 2px;
}

.loom-button:disabled,
.loom-button[aria-disabled="true"] {
  opacity: 0.55;
  cursor: not-allowed;
}

.loom-button--sm { min-height: 32px; padding: 0 12px; font-size: var(--loom-text-sm); }
.loom-button--md { min-height: 38px; padding: 0 16px; font-size: var(--loom-text-sm); }
.loom-button--lg { min-height: 46px; padding: 0 22px; font-size: var(--loom-text-md); }

/* The button that does the thing. */
.loom-button--solid {
  background: var(--loom-color-brand);
  color: var(--loom-color-surface);
  box-shadow: var(--loom-shadow-sm);
}
.loom-button--solid:hover:not(:disabled) {
  background: color-mix(in srgb, var(--loom-color-brand) 88%, black);
}
.loom-button--solid:active:not(:disabled) {
  background: color-mix(in srgb, var(--loom-color-brand) 78%, black);
  box-shadow: none;
}

/* The same intent, quieter — the second button in a row of two. */
.loom-button--soft {
  background: var(--loom-color-brand-tint);
  color: var(--loom-color-brand);
}
.loom-button--soft:hover:not(:disabled) {
  background: color-mix(in srgb, var(--loom-color-brand-tint) 82%, var(--loom-color-brand));
}

.loom-button--outline {
  background: var(--loom-color-surface);
  color: var(--loom-color-ink);
  border-color: var(--loom-color-hairline);
}
.loom-button--outline:hover:not(:disabled) {
  background: var(--loom-color-canvas);
  border-color: color-mix(in srgb, var(--loom-color-hairline) 55%, var(--loom-color-ink));
}

/* Nothing until you point at it: toolbars, table rows, anywhere a border would be noise. */
.loom-button--ghost {
  background: transparent;
  color: var(--loom-color-ink);
}
.loom-button--ghost:hover:not(:disabled) {
  background: var(--loom-color-canvas);
}

/* "This deletes something" is a meaning, so it is a variant rather than a colour someone types. */
.loom-button--destructive {
  background: var(--loom-color-danger);
  color: var(--loom-color-surface);
  box-shadow: var(--loom-shadow-sm);
}
.loom-button--destructive:hover:not(:disabled) {
  background: color-mix(in srgb, var(--loom-color-danger) 88%, black);
}
.loom-button--destructive:focus-visible { outline-color: var(--loom-color-danger); }

/* Reads as a link, still is a button — "cancel" beside a real one. */
.loom-button--link {
  background: transparent;
  color: var(--loom-color-brand);
  padding-left: 0;
  padding-right: 0;
  min-height: 0;
}
.loom-button--link:hover:not(:disabled) { text-decoration: underline; }
`;

const FIELD = `
/* ---- Fields: text, number, multiline, date, select ---------------------------------------- */

.loom-field {
  box-sizing: border-box;
  width: 100%;
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  transition:
    border-color 120ms ease,
    box-shadow 120ms ease,
    background-color 120ms ease;
}

.loom-field::placeholder { color: var(--loom-color-muted); }

/* A focused field says so with the brand colour and a soft ring — the signal shadcn and MUI both
   settled on, because a 1px border change alone is too quiet to notice. */
.loom-field:focus {
  outline: none;
  border-color: var(--loom-color-brand);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--loom-color-brand) 18%, transparent);
}

.loom-field:disabled {
  background: var(--loom-color-canvas);
  color: var(--loom-color-muted);
  cursor: not-allowed;
}

.loom-field--sm { min-height: 32px; padding: 6px 10px; font-size: var(--loom-text-sm); }
.loom-field--md { min-height: 38px; padding: 8px 12px; font-size: var(--loom-text-sm); }
.loom-field--lg { min-height: 46px; padding: 11px 14px; font-size: var(--loom-text-md); }

.loom-field--outline { background: var(--loom-color-surface); }

/* Filled: no border until focus, a tinted well instead. Denser forms read better this way. */
.loom-field--filled {
  background: var(--loom-color-canvas);
  border-color: transparent;
}
.loom-field--filled:focus { background: var(--loom-color-surface); }

/* Underline: one rule, no box. For forms that should disappear into the page. */
.loom-field--underline {
  background: transparent;
  border-width: 0 0 1px 0;
  border-radius: 0;
  padding-left: 0;
  padding-right: 0;
}
.loom-field--underline:focus { box-shadow: none; border-bottom-width: 2px; }

/* A textarea sizes by rows, so a min-height from the size axis would fight it. */
textarea.loom-field { min-height: 0; resize: vertical; line-height: 1.5; }

/* The browser's arrow, kept — a hand-drawn one is a picture of a control rather than the control. */
select.loom-field { cursor: pointer; }
`;

const CHOICE = `
/* ---- Checkbox, switch, radio group ------------------------------------------------------- */

.loom-check {
  display: inline-flex;
  align-items: center;
  gap: var(--loom-space-2);
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
  cursor: pointer;
  user-select: none;
}

.loom-check input[type="checkbox"] {
  appearance: none;
  margin: 0;
  width: 18px;
  height: 18px;
  flex: 0 0 auto;
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-sm);
  background: var(--loom-color-surface);
  cursor: pointer;
  transition: background-color 120ms ease, border-color 120ms ease;
}

/* The tick is drawn rather than fetched: an inline SVG needs no asset and no request, and it
   scales with the box instead of blurring. */
.loom-check input[type="checkbox"]:checked {
  background: var(--loom-color-brand)
    url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='none' stroke='white' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M3 8.5l3.5 3.5L13 5'/%3E%3C/svg%3E")
    center / 12px no-repeat;
  border-color: var(--loom-color-brand);
}

.loom-check input[type="checkbox"]:focus-visible {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 2px;
}

.loom-check--sm { font-size: var(--loom-text-xs); }
.loom-check--lg { font-size: var(--loom-text-md); }
.loom-check--sm input[type="checkbox"] { width: 16px; height: 16px; }
.loom-check--lg input[type="checkbox"] { width: 22px; height: 22px; }

/*
 * The switch: the same checkbox wearing the shape people expect for "on or off, right now" rather
 * than "tick this to agree". It is still a checkbox to a screen reader, which is the point.
 */
.loom-check--switch input[type="checkbox"] {
  width: 38px;
  height: 22px;
  border-radius: var(--loom-radius-pill);
  background: var(--loom-color-hairline);
  border-color: transparent;
  position: relative;
}

.loom-check--switch input[type="checkbox"]::after {
  content: "";
  position: absolute;
  top: 2px;
  left: 2px;
  width: 16px;
  height: 16px;
  border-radius: var(--loom-radius-pill);
  background: var(--loom-color-surface);
  box-shadow: var(--loom-shadow-sm);
  transition: transform 140ms ease;
}

.loom-check--switch input[type="checkbox"]:checked {
  background: var(--loom-color-brand);
  background-image: none;
}

.loom-check--switch input[type="checkbox"]:checked::after { transform: translateX(16px); }

.loom-radios {
  display: flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  margin: 0;
  padding: 0;
  border: 0;
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
}

.loom-radios legend {
  padding: 0;
  margin-bottom: var(--loom-space-1);
  font-weight: var(--loom-weight-medium);
}

.loom-radios label {
  display: inline-flex;
  align-items: center;
  gap: var(--loom-space-2);
  cursor: pointer;
}

.loom-radios input[type="radio"] { accent-color: var(--loom-color-brand); cursor: pointer; }

/* Side by side, for two or three short answers. */
.loom-radios--inline { flex-direction: row; flex-wrap: wrap; gap: var(--loom-space-3); }

/*
 * Cards: each choice is a target the size of a row rather than a 16px circle. On a phone that is
 * the difference between a control people hit and one they miss.
 */
.loom-radios--cards label {
  padding: 10px 12px;
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  background: var(--loom-color-surface);
  transition: border-color 120ms ease, background-color 120ms ease;
}
.loom-radios--cards label:hover {
  border-color: color-mix(in srgb, var(--loom-color-hairline) 55%, var(--loom-color-ink));
}
.loom-radios--cards label:has(input:checked) {
  border-color: var(--loom-color-brand);
  background: var(--loom-color-brand-tint);
}
`;

const SLIDER = `
/* ---- Slider ------------------------------------------------------------------------------ */

.loom-slider {
  width: 100%;
  accent-color: var(--loom-color-brand);
  cursor: pointer;
}

.loom-slider:focus-visible { outline: 2px solid var(--loom-color-brand); outline-offset: 4px; }

.loom-slider--sm { height: 16px; }
.loom-slider--lg { height: 28px; }
`;

const SURFACE = `
/* ---- Frame, list, table ------------------------------------------------------------------ */

/* Plain stays plain. A layout box that suddenly grew a border would change every project that
   already had one, and a frame is the element people use structurally. */

.loom-frame--card {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-sm);
}

.loom-frame--panel {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
}

.loom-frame--section {
  background: var(--loom-color-canvas);
  border-radius: var(--loom-radius-lg);
}

.loom-list--divided > * + * {
  border-top: 1px solid var(--loom-color-hairline);
  padding-top: var(--loom-space-2);
}

.loom-list--cards > * {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  padding: var(--loom-space-3);
}

.loom-table {
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
}

.loom-table th {
  font-weight: var(--loom-weight-medium);
  color: var(--loom-color-muted);
  border-bottom: 1px solid var(--loom-color-hairline);
}

.loom-table td { border-bottom: 1px solid var(--loom-color-hairline); }

.loom-table--striped tbody tr:nth-child(even) { background: var(--loom-color-canvas); }

.loom-table--bordered table { border: 1px solid var(--loom-color-hairline); }
.loom-table--bordered th,
.loom-table--bordered td { border-right: 1px solid var(--loom-color-hairline); }
.loom-table--bordered th:last-child,
.loom-table--bordered td:last-child { border-right: 0; }
`;

const CONTENT = `
/* ---- Text, link, image, icon -------------------------------------------------------------- */

/*
 * The type scale, applied by name. Setting a size by hand still works and still wins — this is
 * what "a heading" means when nobody has said otherwise.
 */
.loom-text { font-family: var(--loom-font-body); color: var(--loom-color-ink); }

.loom-text--body { font-size: var(--loom-text-md); }
.loom-text--display {
  font-size: var(--loom-text-xxl);
  font-weight: var(--loom-weight-bold);
  line-height: 1.1;
  letter-spacing: -0.02em;
}
.loom-text--title {
  font-size: var(--loom-text-xl);
  font-weight: var(--loom-weight-bold);
  line-height: 1.2;
  letter-spacing: -0.01em;
}
.loom-text--subhead {
  font-size: var(--loom-text-lg);
  font-weight: var(--loom-weight-medium);
  line-height: 1.3;
}
.loom-text--caption { font-size: var(--loom-text-xs); color: var(--loom-color-muted); }
.loom-text--code {
  font-family: var(--loom-font-mono);
  font-size: var(--loom-text-sm);
  background: var(--loom-color-canvas);
  border-radius: var(--loom-radius-sm);
  padding: 2px 6px;
}
.loom-text--quote {
  font-size: var(--loom-text-lg);
  line-height: 1.4;
  border-left: 3px solid var(--loom-color-brand);
  padding-left: var(--loom-space-3);
  color: var(--loom-color-muted);
}

.loom-link {
  font-family: var(--loom-font-body);
  color: var(--loom-color-brand);
  text-decoration: none;
  cursor: pointer;
}
.loom-link:hover { text-decoration: underline; }
.loom-link:focus-visible {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 2px;
  border-radius: var(--loom-radius-sm);
}

.loom-link--subtle { color: var(--loom-color-muted); }
.loom-link--subtle:hover { color: var(--loom-color-ink); }

/* A link that looks like a button and is still an anchor — right-clickable, middle-clickable,
   crawlable. That distinction is why Link exists next to Button at all. */
.loom-link--button {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-height: 38px;
  padding: 0 16px;
  font-weight: var(--loom-weight-medium);
  font-size: var(--loom-text-sm);
  background: var(--loom-color-brand);
  color: var(--loom-color-surface);
  border-radius: var(--loom-radius-md);
  box-shadow: var(--loom-shadow-sm);
}
.loom-link--button:hover {
  text-decoration: none;
  background: color-mix(in srgb, var(--loom-color-brand) 88%, black);
}

.loom-image { display: block; max-width: 100%; }
.loom-image--rounded { border-radius: var(--loom-radius-lg); }
.loom-image--circle {
  border-radius: var(--loom-radius-pill);
  aspect-ratio: 1 / 1;
  object-fit: cover;
}
.loom-image--thumb {
  border-radius: var(--loom-radius-md);
  border: 1px solid var(--loom-color-hairline);
  object-fit: cover;
}

.loom-icon { display: inline-block; vertical-align: middle; }
.loom-icon--tinted { color: var(--loom-color-brand); }
.loom-icon--circle,
.loom-icon--square {
  box-sizing: content-box;
  padding: 8px;
  background: var(--loom-color-brand-tint);
  color: var(--loom-color-brand);
}
.loom-icon--circle { border-radius: var(--loom-radius-pill); }
.loom-icon--square { border-radius: var(--loom-radius-md); }
`;


const MEDIA = `
/* ---- Video, audio, carousel, tiles, avatar, embed ------------------------------------------ */

.loom-video,
.loom-embed {
  display: block;
  max-width: 100%;
  background: var(--loom-color-ink);
  border: 0;
}

/* These three arrive rounded, so plain is a decision rather than an absence: square corners, and
   nothing under them. */
.loom-video--plain,
.loom-embed--plain,
.loom-carousel--plain { border-radius: 0; box-shadow: none; }

.loom-video--rounded,
.loom-embed--rounded { border-radius: var(--loom-radius-lg); overflow: hidden; }

.loom-video--card,
.loom-embed--card {
  border-radius: var(--loom-radius-lg);
  overflow: hidden;
  box-shadow: var(--loom-shadow-md);
}

.loom-audio { display: block; width: 100%; }

/* A tinted rail round the player, for a track sitting in a page rather than in a card of its own. */
.loom-audio--soft {
  background: var(--loom-color-canvas);
  border-radius: var(--loom-radius-pill);
  padding: var(--loom-space-2);
}

.loom-audio--card {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  padding: var(--loom-space-2);
  box-shadow: var(--loom-shadow-sm);
}

/*
 * The carousel is a positioning context and nothing else: the picture fills it, and the controls
 * sit over the picture. Sizing belongs to the element the designer drew, not to this.
 */
.loom-carousel {
  position: relative;
  display: block;
  overflow: hidden;
  background: var(--loom-color-canvas);
}

.loom-carousel--rounded { border-radius: var(--loom-radius-lg); }
.loom-carousel--card {
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-md);
}

.loom-carousel__slide {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.loom-carousel__step {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  padding: 0;
  font-size: var(--loom-text-lg);
  line-height: 1;
  color: var(--loom-color-ink);
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-pill);
  box-shadow: var(--loom-shadow-sm);
  cursor: pointer;
}

.loom-carousel__step:hover { background: var(--loom-color-canvas); }
.loom-carousel__step:focus-visible {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 2px;
}

.loom-carousel__step--back { left: var(--loom-space-2); }
.loom-carousel__step--next { right: var(--loom-space-2); }

.loom-carousel__dots {
  position: absolute;
  left: 0;
  right: 0;
  bottom: var(--loom-space-2);
  display: flex;
  justify-content: center;
  gap: 6px;
}

/*
 * A dot is a real button, not a decoration: it is how someone reaches slide four without pressing
 * next three times, and it has to be reachable from a keyboard to be that.
 */
.loom-carousel__dot {
  width: 8px;
  height: 8px;
  padding: 0;
  border: 0;
  border-radius: var(--loom-radius-pill);
  background: var(--loom-color-surface);
  opacity: 0.55;
  cursor: pointer;
  transition: opacity 120ms ease, transform 120ms ease;
}

.loom-carousel__dot.is-on { opacity: 1; transform: scale(1.35); }
.loom-carousel__dot:focus-visible {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 3px;
}

/* The grid itself is emitted inline, because its column width is a number the designer chose. */
.loom-tiles--framed > * {
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  overflow: hidden;
}

.loom-tiles--inset {
  background: var(--loom-color-canvas);
  border-radius: var(--loom-radius-lg);
  padding: var(--loom-space-3);
}

.loom-avatar {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex: 0 0 auto;
  overflow: hidden;
  font-family: var(--loom-font-body);
  font-weight: var(--loom-weight-medium);
  line-height: 1;
  color: var(--loom-color-brand);
  background: var(--loom-color-brand-tint);
  user-select: none;
}

.loom-avatar--circle { border-radius: var(--loom-radius-pill); }
.loom-avatar--rounded { border-radius: var(--loom-radius-md); }
.loom-avatar--square { border-radius: 0; }

.loom-avatar__image {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
`;


const UPLOAD = `
/* ---- Upload fields ------------------------------------------------------------------------ */

/*
 * The real input is hidden and the label is the control: a file input cannot be styled to look like
 * anything, and every design system ends up here. It stays a real input — clicking the label opens
 * the picker, and a keyboard reaches it — rather than a div pretending.
 */
.loom-upload {
  display: inline-flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  align-items: flex-start;
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
}

.loom-upload__input {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip-path: inset(50%);
  white-space: nowrap;
  border: 0;
}

.loom-upload__pick {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--loom-space-2);
  min-height: 38px;
  padding: 0 16px;
  font-weight: var(--loom-weight-medium);
  color: var(--loom-color-ink);
  background: var(--loom-color-surface);
  border: 1px dashed var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  cursor: pointer;
  transition: border-color 120ms ease, background-color 120ms ease;
}

.loom-upload__pick:hover {
  background: var(--loom-color-canvas);
  border-color: var(--loom-color-brand);
}

/* The focus ring belongs on the label, because the input it belongs to is off screen. */
.loom-upload__input:focus-visible + .loom-upload__pick,
.loom-upload:focus-within .loom-upload__pick {
  outline: 2px solid var(--loom-color-brand);
  outline-offset: 2px;
}

.loom-upload__input:disabled + .loom-upload__pick,
.loom-upload__pick[aria-disabled="true"] {
  opacity: 0.6;
  cursor: progress;
}

.loom-upload__preview {
  display: block;
  max-width: 100%;
  max-height: 180px;
  object-fit: cover;
  border-radius: var(--loom-radius-md);
  border: 1px solid var(--loom-color-hairline);
}

/* What was uploaded, for a file that cannot show itself the way a picture can. */
.loom-upload__stored {
  font-size: var(--loom-text-xs);
  color: var(--loom-color-muted);
  overflow-wrap: anywhere;
}

/* Loud, because it is the one input that can refuse what somebody just did. */
.loom-upload__problem {
  color: var(--loom-color-danger);
  font-size: var(--loom-text-xs);
}

.loom-upload--sm .loom-upload__pick { min-height: 32px; padding: 0 12px; font-size: var(--loom-text-sm); }
.loom-upload--lg .loom-upload__pick { min-height: 46px; padding: 0 22px; font-size: var(--loom-text-md); }

/* A tile is a drop-shaped square for a picture; a row is a button with the preview beside it. */
.loom-upload--tile { align-items: stretch; }
.loom-upload--tile .loom-upload__pick { min-height: 96px; border-style: dashed; }
.loom-upload--row { flex-direction: row; align-items: center; }
.loom-upload--row .loom-upload__preview { max-height: 48px; }
`;


const CHART = `
/* ---- Charts ------------------------------------------------------------------------------- */

/*
 * The chart is drawn into a fixed viewBox and the browser scales it, so nothing here has to know
 * how wide the element ended up. Colour comes from the tokens: a restyle moves the bars with it,
 * and there is no rainbow nobody chose.
 */
.loom-chart {
  display: block;
  min-width: 120px;
  min-height: 80px;
  font-family: var(--loom-font-body);
  color: var(--loom-color-ink);
}

.loom-chart__svg { display: block; width: 100%; height: 100%; overflow: visible; }

.loom-chart--card {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-sm);
  padding: var(--loom-space-3);
}

.loom-chart__bar { fill: var(--loom-color-brand); }
.loom-chart__line {
  fill: none;
  stroke: var(--loom-color-brand);
  stroke-width: 2;
  stroke-linecap: round;
  stroke-linejoin: round;
  /* The line keeps its weight whatever the box is scaled to; without this a wide chart draws a
     hairline and a narrow one draws a rope. */
  vector-effect: non-scaling-stroke;
}
.loom-chart__area { fill: var(--loom-color-brand); opacity: 0.14; stroke: none; }
.loom-chart__dot { fill: var(--loom-color-surface); stroke: var(--loom-color-brand); stroke-width: 2; vector-effect: non-scaling-stroke; }
.loom-chart__slice { fill: var(--loom-color-brand); stroke: var(--loom-color-surface); stroke-width: 1; }

.loom-chart__grid {
  stroke: var(--loom-color-hairline);
  stroke-width: 1;
  vector-effect: non-scaling-stroke;
}

/* The numbers on the axis and under the bars. Scaled text would stretch with the box. */
.loom-chart__tick,
.loom-chart__label {
  fill: var(--loom-color-muted);
  font-size: 10px;
  font-family: var(--loom-font-body);
}

.loom-chart__empty {
  display: block;
  padding: var(--loom-space-3);
  color: var(--loom-color-muted);
  font-size: var(--loom-text-sm);
}

/* ---- Stat --------------------------------------------------------------------------------- */

.loom-stat {
  display: inline-flex;
  flex-direction: column;
  gap: 2px;
  font-family: var(--loom-font-body);
  color: var(--loom-color-ink);
}

.loom-stat--card {
  padding: var(--loom-space-3) var(--loom-space-4);
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-sm);
}

.loom-stat__label {
  font-size: var(--loom-text-xs);
  color: var(--loom-color-muted);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.loom-stat__value {
  font-size: var(--loom-text-xl);
  font-weight: var(--loom-weight-bold);
  line-height: 1.1;
  letter-spacing: -0.01em;
}

.loom-stat__note { font-size: var(--loom-text-xs); color: var(--loom-color-muted); }

.loom-stat--sm .loom-stat__value { font-size: var(--loom-text-lg); }
.loom-stat--lg .loom-stat__value { font-size: var(--loom-text-xxl); }
`;


const CALENDAR = `
/* ---- Calendar ----------------------------------------------------------------------------- */

.loom-calendar {
  display: flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
}

.loom-calendar--card {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-sm);
  padding: var(--loom-space-3);
}

.loom-calendar__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--loom-space-2);
}

.loom-calendar__month { font-weight: var(--loom-weight-medium); }

.loom-calendar__step {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  padding: 0;
  font-size: var(--loom-text-md);
  line-height: 1;
  color: var(--loom-color-ink);
  background: transparent;
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
  cursor: pointer;
}

.loom-calendar__step:hover { background: var(--loom-color-canvas); }
.loom-calendar__step:focus-visible { outline: 2px solid var(--loom-color-brand); outline-offset: 2px; }

/* Always six rows, so the grid does not change height between March and April and make everything
   under it jump. */
.loom-calendar__grid {
  display: grid;
  grid-template-columns: repeat(7, minmax(0, 1fr));
  gap: 2px;
  flex: 1 1 auto;
}

.loom-calendar__weekday {
  font-size: var(--loom-text-xs);
  color: var(--loom-color-muted);
  text-align: center;
  padding-bottom: 2px;
}

.loom-calendar__day {
  display: flex;
  flex-direction: column;
  gap: 2px;
  min-height: 46px;
  padding: 4px;
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-sm);
  overflow: hidden;
}

/* The days either side that fill the first and last week are there for the shape, not for reading. */
.loom-calendar__day.is-outside { opacity: 0.45; }
.loom-calendar__day.is-today { border-color: var(--loom-color-brand); }

.loom-calendar__date { font-size: var(--loom-text-xs); color: var(--loom-color-muted); }

.loom-calendar__event {
  font-size: var(--loom-text-xs);
  padding: 1px 4px;
  border-radius: var(--loom-radius-sm);
  background: var(--loom-color-brand-tint);
  color: var(--loom-color-brand);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* Agenda: the same events as a list, which is what a phone wants and what a screen reader reads
   without a fight. */
.loom-calendar__agenda {
  display: flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  margin: 0;
  padding: 0;
  list-style: none;
  overflow-y: auto;
}

.loom-calendar__row {
  display: flex;
  gap: var(--loom-space-2);
  align-items: baseline;
  padding-bottom: var(--loom-space-2);
  border-bottom: 1px solid var(--loom-color-hairline);
}

.loom-calendar__when {
  color: var(--loom-color-muted);
  font-size: var(--loom-text-xs);
  white-space: nowrap;
}

.loom-calendar__empty { color: var(--loom-color-muted); padding: var(--loom-space-3); }

/* ---- Chat --------------------------------------------------------------------------------- */

.loom-chat {
  display: flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
  min-height: 160px;
}

.loom-chat--card {
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-lg);
  box-shadow: var(--loom-shadow-sm);
  padding: var(--loom-space-3);
}

/* The log scrolls, the composer does not: a box that walks down the screen as messages arrive is
   the one thing every chat has to get right. */
.loom-chat__log {
  display: flex;
  flex-direction: column;
  gap: var(--loom-space-2);
  flex: 1 1 auto;
  min-height: 0;
  overflow-y: auto;
}

.loom-chat__message {
  display: flex;
  flex-direction: column;
  gap: 2px;
  align-self: flex-start;
  max-width: 85%;
  padding: 6px 10px;
  background: var(--loom-color-canvas);
  border-radius: var(--loom-radius-md);
}

.loom-chat__message.is-mine {
  align-self: flex-end;
  background: var(--loom-color-brand-tint);
  color: var(--loom-color-brand);
}

.loom-chat--plain .loom-chat__message {
  align-self: stretch;
  max-width: none;
  background: transparent;
  border-radius: 0;
  padding: 4px 0;
  border-bottom: 1px solid var(--loom-color-hairline);
}

.loom-chat__who { font-size: var(--loom-text-xs); color: var(--loom-color-muted); }
.loom-chat__text { overflow-wrap: anywhere; }
.loom-chat__time { font-size: var(--loom-text-xs); color: var(--loom-color-muted); }
.loom-chat__empty { color: var(--loom-color-muted); margin: auto; }

.loom-chat__compose { display: flex; gap: var(--loom-space-2); }

.loom-chat__draft {
  flex: 1 1 auto;
  min-width: 0;
  box-sizing: border-box;
  min-height: 38px;
  padding: 8px 12px;
  font-family: var(--loom-font-body);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-ink);
  background: var(--loom-color-surface);
  border: 1px solid var(--loom-color-hairline);
  border-radius: var(--loom-radius-md);
}

.loom-chat__draft:focus {
  outline: none;
  border-color: var(--loom-color-brand);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--loom-color-brand) 18%, transparent);
}

.loom-chat__send {
  min-height: 38px;
  padding: 0 16px;
  font-family: var(--loom-font-body);
  font-weight: var(--loom-weight-medium);
  font-size: var(--loom-text-sm);
  color: var(--loom-color-surface);
  background: var(--loom-color-brand);
  border: 0;
  border-radius: var(--loom-radius-md);
  cursor: pointer;
}

.loom-chat__send:hover { background: color-mix(in srgb, var(--loom-color-brand) 88%, black); }
.loom-chat__send:focus-visible { outline: 2px solid var(--loom-color-brand); outline-offset: 2px; }
`;

/**
 * The whole stylesheet, in the order a person would read it.
 *
 * A function rather than a constant so a project could one day narrow it; today it takes nothing,
 * because every value in it is already a token the project can move.
 */
export function componentsCss(): string {
  return [
    HEADER,
    BUTTON,
    FIELD,
    CHOICE,
    SLIDER,
    SURFACE,
    CONTENT,
    MEDIA,
    UPLOAD,
    CHART,
    CALENDAR,
  ].join('\n');
}
