import type { Artboard, Snapshot } from '@loom/ir';
import { CompileError, type CompileResult, type EmittedFile } from './types';
import { emitArtboardModule } from './emit/artboard';
import { scaffoldFiles } from './emit/project';
import { pascalCase } from './emit/text';

/**
 * Compile a snapshot into the file set of a runnable Vite + React + TS app.
 *
 * M0 emits static UI only: one module per artboard, the entry artboard rendered by App.
 * Routing (M2), backend nodes (M3) and connectors (M4) plug in here later. Nothing in the
 * snapshot carries a secret (guardrail 1), so nothing secret can reach the emitted repo.
 */
export function compile(snapshot: Snapshot): CompileResult {
  const entry = resolveEntryArtboard(snapshot);
  const names = assignComponentNames(snapshot);

  const files: EmittedFile[] = scaffoldFiles(snapshot.name, snapshot.name);

  for (const [artboardId, artboard] of sortedArtboards(snapshot)) {
    const name = names.get(artboardId)!;
    files.push({
      path: `src/artboards/${name}.tsx`,
      content: emitArtboardModule(snapshot, artboard, name),
    });
  }

  const entryName = names.get(entry.id)!;
  files.push({
    path: 'src/App.tsx',
    content: `// Generated by @loom/compiler. Entry artboard: "${entry.name}".
import ${entryName} from './artboards/${entryName}';

export default function App() {
  return <${entryName} />;
}
`,
  });

  files.sort((a, b) => a.path.localeCompare(b.path));
  return { files };
}

function sortedArtboards(snapshot: Snapshot): [string, Artboard][] {
  return Object.entries(snapshot.artboards).sort(([a], [b]) => a.localeCompare(b));
}

function resolveEntryArtboard(snapshot: Snapshot): Artboard {
  const ids = Object.keys(snapshot.artboards);
  if (ids.length === 0) {
    throw new CompileError('Project has no artboards; nothing to compile.', snapshot.id);
  }

  const entryId = snapshot.entryArtboard ?? ids[0]!;
  const entry = snapshot.artboards[entryId];
  if (!entry) {
    throw new CompileError(`entryArtboard "${entryId}" does not exist.`, snapshot.id);
  }
  return entry;
}

/** Artboard name -> a unique React component name (ids keep collisions deterministic). */
function assignComponentNames(snapshot: Snapshot): Map<string, string> {
  const names = new Map<string, string>();
  const taken = new Set<string>();

  for (const [id, artboard] of sortedArtboards(snapshot)) {
    const base = pascalCase(artboard.name);
    let name = base;
    let n = 2;
    while (taken.has(name)) name = `${base}${n++}`;
    taken.add(name);
    names.set(id, name);
  }

  return names;
}
