import type { Artboard, Snapshot } from '@loom/ir';
import { CompileError, type CompileResult, type EmittedFile } from './types';
import { emitArtboardModule } from './emit/artboard';
import { planRoutes, type RouteInfo } from './emit/routes';
import { planPipelines, validateWires } from './emit/pipeline';
import { emitApiFunction } from './emit/server';
import { scaffoldFiles } from './emit/project';

/**
 * Compile a snapshot into the file set of a runnable Vite + React + TS app.
 *
 * M0 emitted static UI; M2 added the router; M3 adds the backend: an API route node becomes a
 * Vercel serverless function, and the pipelines around it become state, handlers and fetches
 * inside the artboard module. Connectors (M4) plug in here later. Nothing in the snapshot carries
 * a secret (guardrail 1), so nothing secret can reach the emitted repo.
 */
export function compile(snapshot: Snapshot): CompileResult {
  const entry = resolveEntryArtboard(snapshot);
  const routes = planRoutes(snapshot, entry);

  validateFlows(snapshot);
  validateWires(snapshot);

  const files: EmittedFile[] = scaffoldFiles(snapshot.name, snapshot.name);

  // One serverless function per API route node, emitted once even if several screens call it.
  const emittedRoutes = new Set<string>();
  for (const [, artboard] of sortedArtboards(snapshot)) {
    for (const plan of planPipelines(snapshot, artboard)) {
      if (emittedRoutes.has(plan.routePath)) continue;
      emittedRoutes.add(plan.routePath);
      files.push(emitApiFunction(plan));
    }
  }

  for (const [artboardId, artboard] of sortedArtboards(snapshot)) {
    const route = routes.get(artboardId)!;
    files.push({
      path: `src/artboards/${route.componentName}.tsx`,
      content: emitArtboardModule(snapshot, artboard, routes, route.componentName),
    });
  }

  files.push({ path: 'src/App.tsx', content: emitApp(entry, routes) });

  files.sort((a, b) => a.path.localeCompare(b.path));
  return { files };
}

/** The router module: one `<Route>` per artboard, entry first. */
function emitApp(entry: Artboard, routes: Map<string, RouteInfo>): string {
  const ordered = [...routes.values()].sort((a, b) => {
    if (a.artboardId === entry.id) return -1;
    if (b.artboardId === entry.id) return 1;
    return a.componentName.localeCompare(b.componentName);
  });

  const imports = ordered
    .map((route) => `import ${route.componentName} from './artboards/${route.componentName}';`)
    .join('\n');

  const routeElements = ordered
    .map(
      (route) =>
        `        <Route path="${route.path}" element={<${route.componentName} />} />`,
    )
    .join('\n');

  return `// Generated by @loom/compiler. Entry artboard: "${entry.name}".
// Routes come from the artboards and the flow arrows between them — never hand-authored.
import { BrowserRouter, Route, Routes } from 'react-router-dom';
${imports}

export default function App() {
  return (
    <BrowserRouter>
      <Routes>
${routeElements}
      </Routes>
    </BrowserRouter>
  );
}
`;
}

/** Structural checks a flow must pass before any template touches it. */
function validateFlows(snapshot: Snapshot): void {
  for (const flow of Object.values(snapshot.flows)) {
    if (!snapshot.artboards[flow.from]) {
      throw new CompileError(`Flow "${flow.id}" starts at an unknown artboard.`, flow.id);
    }
    const destination = snapshot.artboards[flow.to];
    if (!destination) {
      throw new CompileError(`Flow "${flow.id}" ends at an unknown artboard.`, flow.id);
    }

    const declared = new Set((destination.params ?? []).map((p) => p.name));
    for (const entry of flow.payload ?? []) {
      if (!declared.has(entry.param)) {
        throw new CompileError(
          `Flow "${flow.id}" carries "${entry.param}", which "${destination.name}" does not declare.`,
          flow.id,
        );
      }
    }
  }
}

function sortedArtboards(snapshot: Snapshot): [string, Artboard][] {
  return Object.entries(snapshot.artboards).sort(([a], [b]) => a.localeCompare(b));
}

function resolveEntryArtboard(snapshot: Snapshot): Artboard {
  const ids = Object.keys(snapshot.artboards);
  if (ids.length === 0) {
    throw new CompileError('Project has no artboards; nothing to compile.', snapshot.id);
  }

  const entryId = snapshot.entryArtboard ?? ids[0]!;
  const entry = snapshot.artboards[entryId];
  if (!entry) {
    throw new CompileError(`entryArtboard "${entryId}" does not exist.`, snapshot.id);
  }
  return entry;
}
