-- ===========================================================================
-- O3's gate, set up to be run for real.
--
-- The claim being tested: with loom's emitted policies applied, user A's own
-- session cannot read user B's organisation's rows. Not "the app does not ask
-- for them" — the database refuses.
--
-- HOW TO RUN
--   1. Paste this whole file into the Supabase SQL editor and run it.
--   2. Then, from the repo root:
--        node scripts/rls-breach.mjs
--
-- WHAT IT TOUCHES
--   Only tables prefixed `rls_`. Your existing `notes` table is not read,
--   altered, or enabled for RLS by anything in here.
--
-- TO UNDO
--   drop table if exists rls_notes, rls_members, rls_orgs cascade;
--   drop schema if exists loom_private cascade;
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. A tenanted shape: organisations, who belongs to which, and rows that
--    belong to one.
-- ---------------------------------------------------------------------------
create table if not exists rls_orgs (
  id   uuid primary key default gen_random_uuid(),
  name text not null
);

create table if not exists rls_members (
  id      uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  org_id  uuid not null references rls_orgs (id) on delete cascade,
  role    text not null default 'member'
);

create table if not exists rls_notes (
  id     uuid primary key default gen_random_uuid(),
  title  text not null,
  org_id uuid not null references rls_orgs (id) on delete cascade
);

-- ---------------------------------------------------------------------------
-- 2. Two organisations, two people, one row each.
--
--    Zero rows on both sides would prove nothing — it is what a working policy
--    and a broken one look like alike — so the breach script calls that
--    INCONCLUSIVE and this is what stops it happening.
-- ---------------------------------------------------------------------------
insert into rls_orgs (id, name) values
  ('11111111-1111-1111-1111-111111111111', 'Alpha'),
  ('22222222-2222-2222-2222-222222222222', 'Bravo')
on conflict (id) do nothing;

insert into rls_members (user_id, org_id, role) values
  ('632fe1d1-9177-458b-8408-2bfcc1d90295', '11111111-1111-1111-1111-111111111111', 'admin'),
  ('9a5e380a-78e5-41c4-8bd0-074029502c39', '22222222-2222-2222-2222-222222222222', 'admin')
on conflict do nothing;

insert into rls_notes (id, title, org_id) values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Alpha private note',
   '11111111-1111-1111-1111-111111111111'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Bravo private note',
   '22222222-2222-2222-2222-222222222222')
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- 3. The policies, exactly as @loom/compiler emits them.
--
--    Not written by hand for this test: generated from the same code path a
--    real project gets, so what passes here is what ships.
-- ---------------------------------------------------------------------------

-- Generated by @loom/compiler (docs/V1-COMPLETION.md O3).
--
-- Row-level security: the rules the database itself enforces about who may read and change what.
--
-- Everything the app does to keep one organisation's rows out of another's reach is a
-- convenience until this file is applied. The app narrowing its own queries decides nothing —
-- anyone holding a session can ask the database directly, and this is what answers them.
--
-- Run it against every environment, and read it first: these are the rules that decide who sees
-- what, and they are yours.
--
--   psql "$DATABASE_URL" -f supabase/migrations/loom_row_level_security.sql
--
-- Re-running is safe: every policy is dropped and recreated.

create schema if not exists loom_private;
-- Never exposed over the Data API. A definer function in an exposed schema is callable *as its
-- owner* by anyone who can reach the API, which is the opposite of what it is for.
revoke all on schema loom_private from public, anon, authenticated;

-- Which organisations the person asking belongs to.
--
-- security definer, so reading the memberships here does not re-enter that table's own policies
-- and trip "infinite recursion detected in policy".
--
-- search_path is pinned empty and every name below is schema-qualified. Without that, a caller
-- can point an unqualified name at an object of their own and have it run with this function's
-- privileges — which is the entire reason definer functions are treated carefully.
create or replace function loom_private.orgs_for_current_user()
returns setof uuid
language sql
stable
security definer
set search_path = ''
as $$
  select m."org_id"
  from public."rls_members" m
  where m."user_id" = (select auth.uid());
$$;

revoke all on function loom_private.orgs_for_current_user() from public, anon;
grant execute on function loom_private.orgs_for_current_user() to authenticated;

-- rls_members — who belongs to which organisation.
--
-- Read directly against the user id, never through the helper: the helper reads this table, and
-- a policy here that called it would be the recursion it was written to prevent.
alter table public."rls_members" enable row level security;

drop policy if exists "loom_membership_select" on public."rls_members";
create policy "loom_membership_select"
on public."rls_members"
for select
to authenticated
using ( "user_id" = (select auth.uid()) );

-- rls_orgs — the organisations.
alter table public."rls_orgs" enable row level security;

drop policy if exists "loom_org_select" on public."rls_orgs";
create policy "loom_org_select"
on public."rls_orgs"
for select
to authenticated
using ( id in (select loom_private.orgs_for_current_user()) );

-- rls_notes
alter table public."rls_notes" enable row level security;

drop policy if exists "loom_rls_notes_select" on public."rls_notes";
create policy "loom_rls_notes_select"
on public."rls_notes"
for select
to authenticated
using ( "org_id" in (select loom_private.orgs_for_current_user()) );

-- `with check` on an insert: what the *new* row is allowed to look like. A row filed into
-- somebody else's organisation is refused here rather than merely discouraged in the app.
drop policy if exists "loom_rls_notes_insert" on public."rls_notes";
create policy "loom_rls_notes_insert"
on public."rls_notes"
for insert
to authenticated
with check ( "org_id" in (select loom_private.orgs_for_current_user()) );

-- An update needs both. `using` says which rows may be touched; `with check` says what they
-- may become — without the second, a row can be updated *out of* the organisation it belonged to.
drop policy if exists "loom_rls_notes_update" on public."rls_notes";
create policy "loom_rls_notes_update"
on public."rls_notes"
for update
to authenticated
using ( "org_id" in (select loom_private.orgs_for_current_user()) )
with check ( "org_id" in (select loom_private.orgs_for_current_user()) );

drop policy if exists "loom_rls_notes_delete" on public."rls_notes";
create policy "loom_rls_notes_delete"
on public."rls_notes"
for delete
to authenticated
using ( "org_id" in (select loom_private.orgs_for_current_user()) );
