// Generated by @loom/compiler (docs/V1-COMPLETION.md O3).
//
// Does the database actually refuse? Everything else about tenancy is the app being careful.
// This asks the database directly, the way somebody who did not use your app would.
//
//   Set SUPABASE_URL, SUPABASE_ANON_KEY, A_EMAIL, A_PASSWORD, B_EMAIL, B_PASSWORD
//   then: node scripts/rls-breach.mjs
//
// Two people, in two different organisations, both with a row of their own. It signs in as each,
// asks for everything, and requires that neither can see the other's.

import { readFile } from 'node:fs/promises';

/**
 * The credentials live in `apps/studio/.env.local` already, so this reads them rather than asking
 * anybody to export six variables to run one check. Environment wins where it is set.
 */
async function fromEnvFile() {
  try {
    const raw = await readFile(new URL('../apps/studio/.env.local', import.meta.url), 'utf8');
    return Object.fromEntries(
      raw
        .split(/\r?\n/)
        .filter((line) => line && !line.startsWith('#') && line.includes('='))
        .map((line) => {
          const at = line.indexOf('=');
          return [line.slice(0, at).trim(), line.slice(at + 1).trim().replace(/^["']|["']$/g, '')];
        }),
    );
  } catch {
    return {};
  }
}

const file = await fromEnvFile();
const setting = (name, fallback = '') => process.env[name] ?? file[name] ?? fallback;

const URL_BASE = setting('SUPABASE_URL').replace(/[/]$/, '');
const ANON = setting('SUPABASE_ANON_KEY');
const TABLES = ['rls_notes'];
const TENANT_COLUMN = "org_id";

if (!URL_BASE || !ANON) {
  console.error('Set SUPABASE_URL and SUPABASE_ANON_KEY.');
  process.exit(2);
}

async function signIn(email, password) {
  const response = await fetch(URL_BASE + '/auth/v1/token?grant_type=password', {
    method: 'POST',
    headers: { apikey: ANON, 'content-type': 'application/json' },
    body: JSON.stringify({ email, password }),
  });
  if (!response.ok) throw new Error('Could not sign in as ' + email + ': ' + (await response.text()));
  return (await response.json()).access_token;
}

/** Everything this session can see in a table — no filter, which is the point. */
async function readAll(token, table) {
  const response = await fetch(URL_BASE + '/rest/v1/' + table + '?select=*', {
    headers: { apikey: ANON, authorization: 'Bearer ' + token },
  });
  if (!response.ok) throw new Error('Read failed on ' + table + ': ' + (await response.text()));
  return response.json();
}

const a = await signIn(setting('A_EMAIL', 'rls-a@loom.test'), setting('A_PASSWORD', 'alpha-Pass-123'));
const b = await signIn(setting('B_EMAIL', 'rls-b@loom.test'), setting('B_PASSWORD', 'bravo-Pass-123'));

let failures = 0;

for (const table of TABLES) {
  const seenByA = await readAll(a, table);
  const seenByB = await readAll(b, table);

  const orgsA = new Set(seenByA.map((row) => String(row[TENANT_COLUMN])));
  const orgsB = new Set(seenByB.map((row) => String(row[TENANT_COLUMN])));

  // Neither may see more than one organisation, and never each other's.
  const overlap = [...orgsA].filter((org) => orgsB.has(org));

  if (orgsA.size > 1 || orgsB.size > 1 || overlap.length > 0) {
    failures += 1;
    console.error(
      'LEAK on ' + table + ': A sees [' + [...orgsA] + '], B sees [' + [...orgsB] + ']',
    );
  } else if (seenByA.length === 0 && seenByB.length === 0) {
    // Zero rows on both sides proves nothing — it is what a broken policy and an empty table
    // look like alike. Say so rather than reporting a pass nobody earned.
    failures += 1;
    console.error(
      'INCONCLUSIVE on ' + table + ': neither person can see any row, so this proved nothing. ' +
        'Give each of them a row in their own organisation and run it again.',
    );
  } else {
    console.log('ok ' + table + ': A sees ' + seenByA.length + ' row(s), B sees ' + seenByB.length + ', and neither sees the other organisation.');
  }
}

if (failures > 0) {
  console.error(String.fromCharCode(10) + failures + ' table(s) did not hold. Do not ship this.');
  process.exit(1);
}
console.log(String.fromCharCode(10) + 'Every table held: the database refused, not just the app.');
